import { freezeClone } from "./knowledge-document-admission.service.js";import type { DevelopmentKnowledgeIngestionRequest, DevelopmentKnowledgeIngestionResult, DevelopmentKnowledgeDocumentOutcome } from "../../types/development-knowledge-ingestion.types.js";import type { KnowledgeDocumentService } from "./knowledge-document.service.js";import type { KnowledgeChunkingService } from "./knowledge-chunking.service.js";import type { KnowledgeEmbeddingService } from "./knowledge-embedding.service.js";import type { KnowledgeVectorIndexingService } from "./knowledge-vector-indexing.service.js";import type { KnowledgeVectorIndexDefinition } from "../../types/knowledge-vector-index-definition.types.js";import type { KnowledgeEmbeddingSchemaDefinition } from "../../types/knowledge-embedding.types.js";import type { KnowledgeVectorIndexProjectionRepository } from "../../repositories/knowledge-vector-index-projection.repository.js";

type Dependencies=Readonly<{documents:Pick<KnowledgeDocumentService,"create">;chunks:Pick<KnowledgeChunkingService,"chunkAndPersist">;embeddings:Pick<KnowledgeEmbeddingService,"generate">;indexing:Pick<KnowledgeVectorIndexingService,"index">;projections:Pick<KnowledgeVectorIndexProjectionRepository,"findExactByEntryIdentity">}>;
export class DevelopmentKnowledgeIngestionService{
  public constructor(private readonly dependencies:Dependencies,private readonly schema:KnowledgeEmbeddingSchemaDefinition,private readonly index:KnowledgeVectorIndexDefinition){}
  public async ingest(request:DevelopmentKnowledgeIngestionRequest):Promise<DevelopmentKnowledgeIngestionResult>{
    if(!validRequest(request,this.schema,this.index))return result("VALIDATION_FAILED",request?.mode??"DETERMINISTIC_FIXTURE",[],"INVALID_DEVELOPMENT_INGESTION_REQUEST");
    const outcomes:DevelopmentKnowledgeDocumentOutcome[]=[];
    for(const corpusEntry of request.corpus){
      const lineageBase={chunkSetId:corpusEntry.manifestIdentity.chunkSetId,chunkSetVersion:corpusEntry.manifestIdentity.chunkSetVersion,embeddingSchemaId:this.schema.embeddingSchemaId,embeddingSchemaVersion:this.schema.embeddingSchemaVersion,indexId:this.index.indexId,indexVersion:this.index.indexVersion,namespace:this.index.namespace,embeddingIds:[] as string[],projectionEntryIds:[] as string[]};
      const documentResult=await this.dependencies.documents.create({document:corpusEntry.document});
      if(documentResult.status!=="CREATED"&&documentResult.status!=="ALREADY_EXISTS"){outcomes.push(failed(corpusEntry.document.identity,lineageBase,"FAILED","FAILED",undefined,documentResult.status));continue;}
      const persisted=documentResult.document;
      const chunkResult=await this.dependencies.chunks.chunkAndPersist(persisted,{strategyId:corpusEntry.strategy.strategyId,strategyVersion:corpusEntry.strategy.strategyVersion,manifestIdentity:corpusEntry.manifestIdentity});
      if(chunkResult.status!=="CREATED"&&chunkResult.status!=="ALREADY_EXISTS"){outcomes.push(failed(corpusEntry.document.identity,lineageBase,documentResult.status,"FAILED",undefined,chunkResult.status));continue;}
      const embeddingPrefix=request.mode==="GEMINI"?"GEMINI_EMBED":"DEV_EMBED";const projectionPrefix=request.mode==="GEMINI"?"GEMINI_PROJ":"DEVPROJ";
      const embeddingEntries=chunkResult.chunks.map(chunk=>({chunkIdentity:chunk.identity,embeddingIdentity:{embeddingId:`${embeddingPrefix}:${chunk.identity.chunkId}`,embeddingVersion:1}}));
      const embeddingIds=embeddingEntries.map(value=>value.embeddingIdentity.embeddingId);const projectionEntries=embeddingEntries.map(value=>({entryIdentity:{indexEntryId:`${projectionPrefix}:${value.embeddingIdentity.embeddingId}`,indexEntryVersion:1},embeddingIdentity:value.embeddingIdentity}));const projectionEntryIds=projectionEntries.map(value=>value.entryIdentity.indexEntryId);const lineage={...lineageBase,embeddingIds,projectionEntryIds};
      const embeddingResult=await this.dependencies.embeddings.generate({requestId:`${request.requestId}:EMBED:${corpusEntry.document.identity.documentId}`,requestVersion:request.requestVersion,documentIdentity:persisted.identity,strategy:corpusEntry.strategy,chunkSetIdentity:corpusEntry.manifestIdentity,schemaIdentity:{embeddingSchemaId:this.schema.embeddingSchemaId,embeddingSchemaVersion:this.schema.embeddingSchemaVersion},embeddings:embeddingEntries});
      if(embeddingResult.status!=="COMPLETED"){outcomes.push(failed(corpusEntry.document.identity,lineage,documentResult.status,chunkResult.status,"EMBEDDING_FAILED",embeddingResult.failureCode??embeddingResult.status,embeddingResult.summary));continue;}
      const existingBefore=new Set<string>();for(const entry of projectionEntries){const read=await this.dependencies.projections.findExactByEntryIdentity(entry.entryIdentity.indexEntryId,entry.entryIdentity.indexEntryVersion);if(read.found)existingBefore.add(entry.entryIdentity.indexEntryId);}
      const indexed=await this.dependencies.indexing.index({requestId:`${request.requestId}:INDEX:${corpusEntry.document.identity.documentId}`,requestVersion:request.requestVersion,indexDefinitionIdentity:{indexId:this.index.indexId,indexVersion:this.index.indexVersion},entries:projectionEntries});
      if(indexed.status!=="COMPLETED"){outcomes.push(failed(corpusEntry.document.identity,lineage,documentResult.status,chunkResult.status,undefined,indexed.failureCode??indexed.status,embeddingResult.summary,{created:0,existing:0,conflict:indexed.failureCode?.includes("CONFLICT")?indexed.rejectedEntryIds.length:0,failed:indexed.rejectedEntryIds.length}));continue;}
      let projectionMissing=false;for(const entry of projectionEntries){const read=await this.dependencies.projections.findExactByEntryIdentity(entry.entryIdentity.indexEntryId,entry.entryIdentity.indexEntryVersion);if(!read.found)projectionMissing=true;}
      if(projectionMissing){outcomes.push(failed(corpusEntry.document.identity,lineage,documentResult.status,chunkResult.status,undefined,"PROJECTION_REREAD_FAILED",embeddingResult.summary,{created:0,existing:existingBefore.size,conflict:0,failed:projectionEntries.length-existingBefore.size}));continue;}
      outcomes.push(freezeClone({documentIdentity:corpusEntry.document.identity,status:"COMPLETED",document:documentResult.status,chunks:chunkResult.status,manifest:chunkResult.status,embeddings:{created:embeddingResult.summary.created,existing:embeddingResult.summary.existing,failed:0},projections:{created:projectionEntries.length-existingBefore.size,existing:existingBefore.size,conflict:0,failed:0},lineage}));
    }
    const success=outcomes.filter(value=>value.status==="COMPLETED").length;return result(success===outcomes.length?"COMPLETED":success?"PARTIAL":"FAILED",request.mode,outcomes);
  }
}
const validRequest=(request:DevelopmentKnowledgeIngestionRequest,schema:KnowledgeEmbeddingSchemaDefinition,index:KnowledgeVectorIndexDefinition)=>!!request&&/^[A-Z0-9_.:-]{1,160}$/.test(request.requestId)&&Number.isSafeInteger(request.requestVersion)&&request.requestVersion>0&&["DETERMINISTIC_FIXTURE","GEMINI"].includes(request.mode)&&Array.isArray(request.corpus)&&request.corpus.length===6&&new Set(request.corpus.map(value=>`${value.document.identity.documentId}:${value.document.identity.documentVersion}`)).size===6&&request.corpus.every(value=>value.document.corpus==="PLATFORM_KNOWLEDGE"&&value.document.ownership.ownerType==="SYSTEM")&&index.embeddingSchema.embeddingSchemaId===schema.embeddingSchemaId&&index.embeddingSchema.embeddingSchemaVersion===schema.embeddingSchemaVersion&&index.vectorDimension===768&&schema.vectorDimension===768&&index.similarityMetric==="COSINE"&&schema.similarityMetric==="COSINE"&&((request.mode==="DETERMINISTIC_FIXTURE"&&schema.embeddingSchemaId==="YUDIJI_DEV_DETERMINISTIC_PLATFORM_KNOWLEDGE_768"&&index.indexId==="YUDIJI_ATLAS_DEV_PLATFORM_KNOWLEDGE_DETERMINISTIC_768")||(request.mode==="GEMINI"&&schema.embeddingSchemaId==="YUDIJI_GEMINI_PLATFORM_KNOWLEDGE_EMBEDDING"&&index.indexId==="YUDIJI_ATLAS_PLATFORM_KNOWLEDGE_GEMINI_768"));
const failed=(identity:any,lineage:any,document:any="FAILED",chunks:any="FAILED",embeddingStage?:string,code="PIPELINE_FAILED",embeddingSummary?:any,projections={created:0,existing:0,conflict:0,failed:0}):DevelopmentKnowledgeDocumentOutcome=>freezeClone({documentIdentity:identity,status:"FAILED",document:["CREATED","ALREADY_EXISTS"].includes(document)?document:"FAILED",chunks:["CREATED","ALREADY_EXISTS"].includes(chunks)?chunks:"FAILED",manifest:["CREATED","ALREADY_EXISTS"].includes(chunks)?chunks:"FAILED",embeddings:embeddingSummary?{created:embeddingSummary.created,existing:embeddingSummary.existing,failed:embeddingSummary.failed}:{created:0,existing:0,failed:embeddingStage?1:0},projections,failureCode:code,lineage});
const result=(status:DevelopmentKnowledgeIngestionResult["status"],mode:DevelopmentKnowledgeIngestionResult["mode"],outcomes:readonly DevelopmentKnowledgeDocumentOutcome[],failureCode?:string):DevelopmentKnowledgeIngestionResult=>{const count=(field:"document"|"chunks"|"manifest",value:string)=>outcomes.filter(outcome=>outcome[field]===value).length;const sum=(field:"embeddings"|"projections",key:string)=>outcomes.reduce((total,outcome)=>total+Number((outcome[field] as any)[key]??0),0);return freezeClone({status,mode,outcomes,summary:{documents:{created:count("document","CREATED"),existing:count("document","ALREADY_EXISTS"),failed:count("document","FAILED")},chunks:{created:count("chunks","CREATED"),existing:count("chunks","ALREADY_EXISTS"),failed:count("chunks","FAILED")},manifests:{created:count("manifest","CREATED"),existing:count("manifest","ALREADY_EXISTS"),failed:count("manifest","FAILED")},embeddings:{created:sum("embeddings","created"),existing:sum("embeddings","existing"),failed:sum("embeddings","failed")},projections:{created:sum("projections","created"),existing:sum("projections","existing"),conflict:sum("projections","conflict"),failed:sum("projections","failed")}},...(failureCode?{failureCode}:{})});};
