import mongoose from "mongoose";
import { pathToFileURL } from "node:url";
import { createMongoAtlasVectorAdapterConfig } from "../../src/config/mongo-atlas-vector.config.js";
import { MONGO_ATLAS_PLATFORM_KNOWLEDGE_VECTOR_INDEX_DEFINITION } from "../../src/registries/knowledge-vector-index-definition.registry.js";
import { MongoAtlasVectorIndexSpecificationService } from "../../src/services/mongo-atlas-vector-index-specification.service.js";
import { MongoAtlasVectorIndexAdministrationService } from "../../src/services/mongo-atlas-vector-index-administration.service.js";

export const validateAtlasIndexCreationGuard=(env:NodeJS.ProcessEnv)=>{if(env.YUDIJI_ATLAS_VECTOR_INDEX_CREATION_CONFIRMED!=="true")throw new Error("ATLAS_VECTOR_INDEX_CREATION_NOT_CONFIRMED");if(env.YUDIJI_ATLAS_VECTOR_LIVE_VALIDATION_CONFIRMED!=="true")throw new Error("ATLAS_VECTOR_LIVE_VALIDATION_NOT_CONFIRMED");if(env.NODE_ENV==="production")throw new Error("ATLAS_VECTOR_INDEX_CREATION_PRODUCTION_FORBIDDEN");if(!env.MONGO_URI?.trim())throw new Error("MONGO_URI_REQUIRED");if(!env.YUDIJI_ATLAS_VECTOR_DATABASE||!env.YUDIJI_ATLAS_VECTOR_COLLECTION||!env.YUDIJI_ATLAS_VECTOR_INDEX_NAME)throw new Error("ATLAS_VECTOR_EXPLICIT_TARGET_REQUIRED");const config=createMongoAtlasVectorAdapterConfig(env);if(/prod|production/i.test(config.databaseName)||!/dev|test|sandbox/i.test(config.databaseName))throw new Error("ATLAS_VECTOR_DEVELOPMENT_DATABASE_REQUIRED");if(config.collectionName!=="knowledgevectorindexprojections"||config.vectorIndexName!=="yudiji_atlas_platform_knowledge_gemini_768_v1")throw new Error("ATLAS_VECTOR_TARGET_NOT_APPROVED");return config;};
export const run=async(env:NodeJS.ProcessEnv=process.env)=>{const config=validateAtlasIndexCreationGuard(env);const specification=new MongoAtlasVectorIndexSpecificationService().create(MONGO_ATLAS_PLATFORM_KNOWLEDGE_VECTOR_INDEX_DEFINITION,config);await mongoose.connect(env.MONGO_URI!,{dbName:config.databaseName});try{const collection=mongoose.connection.db!.collection(config.collectionName);const result=await new MongoAtlasVectorIndexAdministrationService(collection as any,config.requestTimeoutMs,config.totalDeadlineMs).ensure(specification,true,1000);process.stdout.write(`${JSON.stringify({result,specification:{name:specification.name,digest:specification.digest,definition:specification.definition}},null,2)}\n`);if(!["INDEX_QUERYABLE","INDEX_BUILDING"].includes(result.status))process.exitCode=1;}finally{await mongoose.disconnect();}};
if(import.meta.url===pathToFileURL(process.argv[1]??"").href)run().catch(error=>{process.stderr.write(`${error instanceof Error?error.message:"ATLAS_VECTOR_INDEX_COMMAND_FAILED"}\n`);process.exitCode=1;});
