import type { KnowledgeVectorSearchPort } from "../../src/ports/knowledge-vector-search.port.js";
import type { KnowledgeVectorIndexEntry } from "../../src/types/knowledge-vector-index-write.types.js";
import type { KnowledgeVectorSearchRequest, KnowledgeVectorSearchResult } from "../../src/types/knowledge-retrieval.types.js";
import { freezeClone } from "../../src/services/knowledge/knowledge-document-admission.service.js";
export class InMemoryKnowledgeVectorSearchPort implements KnowledgeVectorSearchPort {
 public calls=0; public constructor(private readonly entries:readonly KnowledgeVectorIndexEntry[],private readonly forceFailure=false){}
 public async search(r:KnowledgeVectorSearchRequest):Promise<KnowledgeVectorSearchResult>{this.calls++;if(this.forceFailure)return Object.freeze({status:"SEARCH_FAILED",candidates:[],failureCode:"TEST_SEARCH_FAILED"});if(!(r.asOf instanceof Date)||!Number.isFinite(r.asOf.getTime()))return Object.freeze({status:"VALIDATION_FAILED",candidates:[],failureCode:"AS_OF_INVALID"});if(r.queryVector.length!==r.vectorDimension||r.queryVector.some(x=>!Number.isFinite(x)))return Object.freeze({status:"DIMENSION_MISMATCH",candidates:[]});if(r.metric!=="COSINE")return Object.freeze({status:"METRIC_NOT_SUPPORTED",candidates:[]});const values=this.entries.filter(e=>e.indexDefinitionIdentity.indexId===r.index.indexId&&e.indexDefinitionIdentity.indexVersion===r.index.indexVersion&&e.namespace===r.namespace&&r.eligibleDocuments.some(d=>d.documentId===e.documentIdentity.documentId&&d.documentVersion===e.documentIdentity.documentVersion)&&r.trustLevels.includes(e.trustLevel)&&e.corpus===r.corpus).map(e=>({indexEntryId:e.identity.indexEntryId,indexEntryVersion:e.identity.indexEntryVersion,index:e.indexDefinitionIdentity,namespace:e.namespace,embeddingIdentity:e.embeddingIdentity,documentIdentity:e.documentIdentity,chunkSetIdentity:e.chunkSetIdentity,chunkIdentity:e.chunkIdentity,chunkDigest:e.chunkDigest,vectorDigest:e.vectorDigest,providerScore:cosine(r.queryVector,e.vector),searchableMetadata:e.searchableMetadata})).sort((a,b)=>b.providerScore-a.providerScore||a.indexEntryId.localeCompare(b.indexEntryId)).slice(0,r.candidateLimit).map((value,providerOrdinal)=>({...value,providerOrdinal}));return freezeClone({status:values.length?"COMPLETED":"NO_CANDIDATES",candidates:values});}
}
const cosine=(a:readonly number[],b:readonly number[])=>{if(a.length!==b.length)return Number.NaN;const dot=a.reduce((s,x,i)=>s+x*b[i]!,0),aa=Math.sqrt(a.reduce((s,x)=>s+x*x,0)),bb=Math.sqrt(b.reduce((s,x)=>s+x*x,0));return aa&&bb?dot/(aa*bb):0;};
