import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { StaticFactorRegistry } from "../../../src/registries/factor.registry.js";
import { EvidenceFactorCompatibilityService } from "../../../src/services/evidence-factor-compatibility.service.js";
import { CompiledShadowObservationAssemblyService } from "../../../src/services/compiled-shadow-observation-assembly.service.js";
import type { EvidenceReadRecord } from "../../../src/types/evidence-lifecycle.types.js";

const AS_OF = new Date("2026-08-05T10:02:00.000Z");
const factor = { factorKey: "MARKET.PRICE" as const, version: 1, displayName: "Market price", description: "Canonical market price", status: "ACTIVE" as const, valueTypes: ["NUMBER" as const], subjectTypes: ["INSTRUMENT" as const], unit: { policy: "REQUIRED" as const }, freshness: { kind: "MAX_AGE" as const, maxAgeMs: 300_000 }, scoringEligibility: "ELIGIBLE" as const };
const binding = (order = 0) => ({ bindingId: `PRICE_${order}`, order, factor: { factorKey: "MARKET.PRICE" as const, factorVersion: 1 }, subjectBinding: { type: "TRADED_INSTRUMENT" as const }, evaluator: { evaluatorId: "PRICE_EVALUATOR", evaluatorVersion: 1, configurationId: "PRICE_CONFIG", configurationVersion: 1 }, relationshipType: "DIRECT" as const, requirementLevel: "MANDATORY" as const, optionalBehavior: null, weight: 1, provider: { providerBindingId: "PRICE_PROVIDERS", providerBindingVersion: 1, resolutionPolicyId: "PRICE_POLICY", resolutionPolicyVersion: 1 }, executionPolicies: { aggregationPolicyId: "AGG", aggregationPolicyVersion: 1, normalizationPolicyId: "NORM", normalizationPolicyVersion: 1, decisionBandPolicyId: "BANDS", decisionBandPolicyVersion: 1 } });
const rulebook = (bindings = [binding()]) => ({ identity: { rulebookId: "BTC_PRICE_RULEBOOK", rulebookVersion: 1 }, source: { templateId: "BTC_PRICE_TEMPLATE", templateVersion: 1 }, compilation: { compilerId: "COMPILER", compilerVersion: 1, compilationInputHash: "a".repeat(64), compiledAt: new Date("2026-08-05T09:00:00.000Z") }, factorBindings: bindings, crossFactorPolicy: null, decisionPolicy: null });
const executionBinding = { bindingId: "BTC_PRICE_EXECUTION", bindingVersion: 1, sourceTemplate: { templateId: "BTC_PRICE_TEMPLATE", templateVersion: 1, scope: "SYSTEM" as const }, compiledRulebook: { rulebookId: "BTC_PRICE_RULEBOOK", rulebookVersion: 1 }, createdAt: new Date("2026-08-05T09:01:00.000Z") };
const evidence = (id = "EVIDENCE_BTC_PRICE", overrides: Record<string, unknown> = {}): EvidenceReadRecord => ({ evidenceId: id, recordType: "OBSERVATION", factorKey: "MARKET.PRICE", deduplicationKey: `dedup-${id}`, subject: { type: "INSTRUMENT", key: "BTCUSDT" }, provenance: { sourceType: "MARKET_DATA", provider: "binance-public-price", sourcePublishedAt: new Date("2026-08-05T10:00:00.000Z") }, value: { type: "NUMBER", numberValue: 65000, unit: "USDT" }, observedAt: new Date("2026-08-05T10:00:00.000Z"), confidence: 0.9, schemaVersion: "1.0", createdAt: new Date("2026-08-05T10:01:00.000Z"), ...overrides } as EvidenceReadRecord);
const attestation = (id = "EVIDENCE_BTC_PRICE", overrides: Record<string, unknown> = {}) => ({ attestationId: `ATTESTATION_${id}`, attestationVersion: 1, evidenceId: id, providerBinding: { providerBindingId: "PRICE_PROVIDERS", providerBindingVersion: 1 }, resolutionPolicy: { policyId: "PRICE_POLICY", policyVersion: 1 }, selectedProviderKey: "BINANCE", selectedProviderType: "DIRECT", resolutionStatus: "RESOLVED", confidenceAdjustment: 0, warningCodes: [], resolvedAt: new Date("2026-08-05T10:00:00.000Z"), createdAt: new Date("2026-08-05T10:01:00.000Z"), ...overrides });
const create = (options: { replayFixtureEligible?: boolean; authorityLookups?: { count: number } } = {}) => new CompiledShadowObservationAssemblyService({
  compatibility: new EvidenceFactorCompatibilityService({ factorRegistry: new StaticFactorRegistry([factor]) }),
  factorDefinitions: { getExact: (key, version) => key === "MARKET.PRICE" && version === 1 ? { definition: factor, compileEligible: true } : null },
  providerBindings: { getExact: (id, version) => id === "PRICE_PROVIDERS" && version === 1 ? { providerBindingId: id, providerBindingVersion: version, factorKey: "MARKET.PRICE", factorVersion: 1, orderedProviderKeys: ["BINANCE"], compileEligible: true } : null },
  resolutionPolicies: { getExact: (id, version) => id === "PRICE_POLICY" && version === 1 ? { definition: { policyId: id, policyVersion: version }, compileEligible: true } as never : null },
  providerAuthorities: { getExact: (key) => {
    if (options.authorityLookups) options.authorityLookups.count++;
    return key === "BINANCE" ? { providerDefinition: { providerKey: "BINANCE", displayName: "Binance", providerType: "DIRECT", authorityLevel: "EXCHANGE", costTier: "FREE", supportedFactorKeys: ["MARKET.PRICE"], enabled: true }, evidenceProvenanceProvider: "binance-public-price", capabilities: { compileEligible: true, liveExecutionEligible: true, replayFixtureEligible: options.replayFixtureEligible ?? true } } : null;
  } },
});
const request = (overrides: Record<string, unknown> = {}) => ({ rulebook: rulebook(), executionBinding, asOf: AS_OF, tradedInstrument: { type: "INSTRUMENT", key: "BTCUSDT" }, evidence: [evidence()], attestations: [attestation()], ...overrides });

test("assembles the complete canonical BTC MARKET.PRICE proof without I/O", () => { const output = create().assemble(request()); assert.equal(output.status, "COMPLETED"); assert.equal(output.observations.length, 1); assert.deepEqual(output.observations[0]?.providerAttestation, { providerBindingId: "PRICE_PROVIDERS", providerBindingVersion: 1, resolutionPolicyId: "PRICE_POLICY", resolutionPolicyVersion: 1, selectedProviderKey: "BINANCE", resolutionOutcome: "RESOLVED" }); assert.equal(output.traces[0]?.availabilityStatus, "ELIGIBLE"); assert.equal(output.traces[0]?.freshness?.status, "FRESH"); });
test("preserves live-provider provenance while requiring replay eligibility without runner lookup", () => { const lookups = { count: 0 }; const output = create({ authorityLookups: lookups }).assemble(request()); assert.equal(output.status, "COMPLETED"); assert.equal(output.traces[0]?.evidenceProvenanceProvider, "binance-public-price"); assert.equal(lookups.count, 1); const denied = create({ replayFixtureEligible: false }).assemble(request()); assert.equal(denied.status, "NO_USABLE_EVIDENCE"); assert.equal(denied.traces[0]?.reasonCodes[0], "PROVIDER_AUTHORITY_INELIGIBLE"); });
test("A4 source has no runner-registry dependency or lookup", () => { const source = readFileSync(new URL("../../../src/services/compiled-shadow-observation-assembly.service.ts", import.meta.url), "utf8"); assert.doesNotMatch(source, /ProviderResolutionRunnerRegistry|providerRegistrations|runnerRegistry|\.runner\b/); assert.match(source, /providerAuthorities\.getExact/); });
test("enforces publication ingestion and attestation persistence time with equality accepted", () => { for (const [field, value, reason] of [["publication", new Date("2026-08-05T10:03:00.000Z"), "NOT_YET_PUBLISHED"], ["created", new Date("2026-08-05T10:03:00.000Z"), "NOT_YET_INGESTED"], ["attestation", new Date("2026-08-05T10:03:00.000Z"), "ATTESTATION_NOT_YET_PERSISTED"]] as const) { const E = evidence(); const A = attestation(); if (field === "publication") E.provenance.sourcePublishedAt = value; if (field === "created") (E as any).createdAt = value; if (field === "attestation") (A as any).createdAt = value; const output = create().assemble(request({ evidence: [E], attestations: [A] })); assert.equal(output.status, "NO_USABLE_EVIDENCE"); assert.equal(output.traces[0]?.reasonCodes[0], reason); } const equal = evidence("EQUAL", { observedAt: AS_OF, createdAt: AS_OF, provenance: { sourceType: "MARKET_DATA", provider: "binance-public-price", sourcePublishedAt: AS_OF } }); assert.equal(create().assemble(request({ evidence: [equal], attestations: [attestation("EQUAL", { createdAt: AS_OF })] })).status, "COMPLETED"); });
test("fails closed for missing timestamps without substitution", () => { for (const [E, A, reason] of [[evidence("A", { provenance: { sourceType: "MARKET_DATA", provider: "binance-public-price" } }), attestation("A"), "PUBLICATION_TIME_MISSING"], [evidence("B", { createdAt: undefined }), attestation("B"), "INGESTION_TIME_MISSING"], [evidence("C"), attestation("C", { createdAt: undefined }), "ATTESTATION_CREATED_TIME_MISSING"]] as const) { const output = create().assemble(request({ evidence: [E], attestations: [A] })); assert.equal(output.traces[0]?.reasonCodes[0], reason); } });
test("requires one exact attestation and exact lineage/provider mapping", () => { const cases = [[[], "PROVIDER_ATTESTATION_MISSING"], [[attestation(), attestation("EVIDENCE_BTC_PRICE", { attestationId: "ATTESTATION_TWO" })], "PROVIDER_ATTESTATION_AMBIGUOUS"], [[attestation("EVIDENCE_BTC_PRICE", { providerBinding: { providerBindingId: "OTHER", providerBindingVersion: 1 } })], "PROVIDER_BINDING_MISMATCH"], [[attestation("EVIDENCE_BTC_PRICE", { resolutionPolicy: { policyId: "OTHER", policyVersion: 1 } })], "RESOLUTION_POLICY_MISMATCH"]] as const; for (const [attestations, reason] of cases) { const output = create().assemble(request({ attestations })); assert.equal(output.traces[0]?.reasonCodes[0], reason); } const wrongProvider = evidence("EVIDENCE_BTC_PRICE", { provenance: { sourceType: "MARKET_DATA", provider: "BINANCE", sourcePublishedAt: new Date("2026-08-05T10:00:00.000Z") } }); assert.equal(create().assemble(request({ evidence: [wrongProvider] })).traces[0]?.reasonCodes[0], "PROVIDER_PROVENANCE_MISMATCH"); });
test("projects every detailed status while retaining degraded details", () => { for (const [status, projected] of [["RESOLVED", "RESOLVED"], ["DEGRADED_PRIMARY_USED", "RESOLVED"], ["FALLBACK_USED", "FALLBACK"], ["PROXY_USED", "PROXY"]] as const) { const A = attestation("EVIDENCE_BTC_PRICE", { resolutionStatus: status, confidenceAdjustment: status === "RESOLVED" ? 0 : -0.1, warningCodes: status === "RESOLVED" ? [] : ["PREFERRED_PROVIDER_DEGRADED"] }); const output = create().assemble(request({ attestations: [A] })); assert.equal(output.observations[0]?.providerAttestation.resolutionOutcome, projected); assert.equal(output.traces[0]?.detailedResolutionStatus, status); assert.deepEqual(output.traces[0]?.warningCodes, A.warningCodes); } });
test("applies availability before lifecycle so future revocation cannot rewrite history", () => { const revocation = evidence("REVOCATION", { recordType: "REVOCATION", value: undefined, revokesEvidenceId: "EVIDENCE_BTC_PRICE", reasonCode: "CORRECTION", observedAt: new Date("2026-08-05T10:01:30.000Z"), provenance: { sourceType: "MANUAL", provider: "binance-public-price", sourcePublishedAt: new Date("2026-08-05T10:03:00.000Z") }, createdAt: new Date("2026-08-05T10:03:00.000Z") }); const output = create().assemble(request({ evidence: [evidence(), revocation], attestations: [attestation(), attestation("REVOCATION", { createdAt: new Date("2026-08-05T10:03:00.000Z") })] })); assert.equal(output.status, "COMPLETED"); assert.equal(output.traces[0]?.lifecycleStatus, "ACTIVE"); });
test("historically known revocation and supersession apply after availability filtering", () => { const revocation = evidence("REVOCATION", { recordType: "REVOCATION", value: undefined, revokesEvidenceId: "EVIDENCE_BTC_PRICE", reasonCode: "CORRECTION", observedAt: new Date("2026-08-05T10:01:30.000Z") }); const revoked = create().assemble(request({ evidence: [evidence(), revocation], attestations: [attestation(), attestation("REVOCATION")] })); assert.equal(revoked.status, "NO_USABLE_EVIDENCE"); assert.equal(revoked.traces[0]?.lifecycleStatus, "REVOKED"); const replacement = evidence("REPLACEMENT", { observedAt: new Date("2026-08-05T10:01:30.000Z"), supersedesEvidenceId: "EVIDENCE_BTC_PRICE" }); const superseded = create().assemble(request({ evidence: [evidence(), replacement], attestations: [attestation(), attestation("REPLACEMENT")] })); assert.equal(superseded.status, "COMPLETED"); assert.equal(superseded.observations[0]?.value, 65000); assert.equal(superseded.traces[0]?.evidenceId, "REPLACEMENT"); });
test("rejects stale, mismatched, and ambiguous candidates without recency selection", () => { assert.equal(create().assemble(request({ evidence: [evidence("OLD", { observedAt: new Date("2026-08-05T09:00:00.000Z") })], attestations: [attestation("OLD")] })).traces[0]?.reasonCodes[0], "FRESHNESS_REJECTED"); assert.equal(create().assemble(request({ evidence: [evidence("WRONG", { subject: { type: "INSTRUMENT", key: "ETHUSDT" } })], attestations: [attestation("WRONG")] })).traces[0]?.reasonCodes[0], "SUBJECT_MISMATCH"); const ambiguous = create().assemble(request({ evidence: [evidence("E1"), evidence("E2")], attestations: [attestation("E1"), attestation("E2")] })); assert.equal(ambiguous.status, "INVALID_EVIDENCE_SET"); assert.equal(ambiguous.observations.length, 0); assert.equal(ambiguous.traces[0]?.reasonCodes[0], "AMBIGUOUS_CANDIDATES"); });
test("returns detached deeply frozen deterministic output with cloned Dates", () => { const source = request(); const first = create().assemble(source); const second = create().assemble(request()); assert.deepEqual(first, second); assert(Object.isFrozen(first)); assert(Object.isFrozen(first.traces[0]!)); assert(Object.isFrozen(first.observations[0]!)); assert.notEqual(first.asOf, source.asOf); assert.notEqual(first.observations[0]?.observedAt, source.evidence[0]?.observedAt); assert.equal((source.evidence[0] as any).value.numberValue, 65000); });
