import assert from "node:assert/strict";
import test from "node:test";
import { CompiledShadowExecutionService } from "../../../src/services/compiled-shadow-execution.service.js";

const AS_OF = new Date("2026-08-05T10:00:00.000Z");
const REQUESTED_AT = new Date("2026-08-05T10:00:01.000Z");
const sourceTemplate = { templateId: "BTC_SYSTEM_TEMPLATE", templateVersion: 1, scope: "SYSTEM" as const };
const executionBinding = { bindingId: "BTC_EXECUTION", bindingVersion: 1, sourceTemplate, compiledRulebook: { rulebookId: "BTC_RULEBOOK", rulebookVersion: 1 }, createdAt: new Date("2026-08-05T09:00:00.000Z") };
const factorBinding = { bindingId: "PRICE", order: 0, factor: { factorKey: "MARKET.PRICE", factorVersion: 1 }, subjectBinding: { type: "TRADED_INSTRUMENT" }, evaluator: { evaluatorId: "PRICE", evaluatorVersion: 1, configurationId: "PRICE", configurationVersion: 1 }, relationshipType: "DIRECT", requirementLevel: "MANDATORY", optionalBehavior: null, weight: 1, provider: { providerBindingId: "PRICE_PROVIDERS", providerBindingVersion: 1, resolutionPolicyId: "PRICE_POLICY", resolutionPolicyVersion: 1 }, executionPolicies: { aggregationPolicyId: "AGG", aggregationPolicyVersion: 1, normalizationPolicyId: "NORM", normalizationPolicyVersion: 1, decisionBandPolicyId: "BANDS", decisionBandPolicyVersion: 1 } };
const rulebook = { identity: { rulebookId: "BTC_RULEBOOK", rulebookVersion: 1 }, source: { templateId: "BTC_SYSTEM_TEMPLATE", templateVersion: 1 }, compilation: { compilerId: "COMPILER", compilerVersion: 1, compilationInputHash: "a".repeat(64), compiledAt: new Date("2026-08-05T09:00:00.000Z") }, factorBindings: [factorBinding], crossFactorPolicy: null, decisionPolicy: null };
const evidence = { evidenceId: "EVIDENCE_PRICE", recordType: "OBSERVATION", factorKey: "MARKET.PRICE", deduplicationKey: "price", subject: { type: "INSTRUMENT", key: "BTCUSDT" }, provenance: { sourceType: "MARKET_DATA", provider: "binance", sourcePublishedAt: new Date("2026-08-05T09:59:00.000Z") }, value: { type: "NUMBER", numberValue: 65000, unit: "USDT" }, observedAt: new Date("2026-08-05T09:59:00.000Z"), confidence: 1, schemaVersion: "1.0", createdAt: new Date("2026-08-05T09:59:01.000Z") };
const attestation = { attestationId: "ATTESTATION_PRICE", attestationVersion: 1, evidenceId: "EVIDENCE_PRICE", providerBinding: { providerBindingId: "PRICE_PROVIDERS", providerBindingVersion: 1 }, resolutionPolicy: { policyId: "PRICE_POLICY", policyVersion: 1 }, selectedProviderKey: "BINANCE", selectedProviderType: "DIRECT", resolutionStatus: "RESOLVED", confidenceAdjustment: 0, warningCodes: [], resolvedAt: new Date("2026-08-05T09:59:00.000Z"), createdAt: new Date("2026-08-05T09:59:01.000Z") };
const observation = { factor: { factorKey: "MARKET.PRICE", factorVersion: 1 }, subject: { type: "INSTRUMENT", key: "BTCUSDT" }, valueType: "NUMBER", value: 65000, unit: "USDT", observedAt: new Date("2026-08-05T09:59:00.000Z"), confidence: 1, providerAttestation: { providerBindingId: "PRICE_PROVIDERS", providerBindingVersion: 1, resolutionPolicyId: "PRICE_POLICY", resolutionPolicyVersion: 1, selectedProviderKey: "BINANCE", resolutionOutcome: "RESOLVED" } };
const assembly = (status: string = "COMPLETED", observations: any[] = [observation]) => ({ status, rulebook: rulebook.identity, executionBinding: { bindingId: executionBinding.bindingId, bindingVersion: 1 }, asOf: AS_OF, observations, traces: [{ bindingIndex: 0, disposition: observations.length ? "PROJECTED" : "OMITTED", reasonCodes: [] }], counts: { bindingCount: 1, projectedCount: observations.length, omittedCount: observations.length ? 0 : 1, invalidCount: 0 }, diagnostics: [], failureStage: null });
const compiled = (status = "COMPLETED") => ({ status, rulebook: { identity: rulebook.identity, source: rulebook.source, compilation: rulebook.compilation }, requestRulebook: rulebook.identity, evaluatedAt: AS_OF, bindingTraces: [], counts: { bindingCount: 1, includedCount: 1, partialCount: 0, omittedCount: 0, blockingCount: 0, failedCount: 0 }, policyLineage: {}, aggregation: {}, aggregateScore: 80, normalization: {}, normalizedScore: 80, decision: {}, decisionBand: { label: "TAKE_TRADE" }, includedWeight: 1, failedBindingOrder: null, failureCode: status === "FAILED" ? "BINDING_EXECUTION_FAILED" : null, stageFailureCode: null });
const request = (overrides: Record<string, unknown> = {}) => ({ sourceTemplate, asOf: AS_OF, tradedInstrument: { type: "INSTRUMENT", key: "BTCUSDT" }, shadowExecutionIdentity: { shadowExecutionId: "SHADOW_1", authoritativeScoreCheckId: "SCORE_CHECK_1", requestedAt: REQUESTED_AT }, ...overrides });

const harness = (overrides: Record<string, any> = {}) => {
  const calls = { binding: 0, rulebook: 0, evidence: 0, attestation: 0, assembly: 0, compiled: 0, policy: 0, parity: 0 };
  const deps: any = {
    executionBindingReader: { getExactForSourceTemplate: async () => { calls.binding++; return { found: true, binding: executionBinding }; } },
    compiledRulebookReader: { getExact: async () => { calls.rulebook++; return { found: true, rulebook }; } },
    evidenceReader: { read: async () => { calls.evidence++; return { history: [evidence], complete: true }; } },
    attestationReader: { getExactByEvidenceId: async () => { calls.attestation++; return { found: true, attestation }; } },
    observationAssembler: { assemble: () => { calls.assembly++; return assembly(); } },
    compiledRulebookExecutor: { execute: () => { calls.compiled++; return compiled(); } },
    parityPolicyValidator: { validate: (policy: any) => { calls.policy++; return { valid: true, policy }; } },
    parityComparisonService: { compare: () => { calls.parity++; return { compared: true, result: { policy: { policyId: "PARITY", policyVersion: 1 }, overallComparability: "FULLY_COMPARABLE" } }; } },
    ...overrides,
  };
  return { service: new CompiledShadowExecutionService(deps), calls, deps };
};

test("runs the exact standalone BTC shadow pipeline once and preserves lineage", async () => { const h = harness(); const result = await h.service.execute(request()); assert.equal(result.status, "COMPLETED"); assert.deepEqual(h.calls, { binding: 1, rulebook: 1, evidence: 1, attestation: 1, assembly: 1, compiled: 1, policy: 0, parity: 0 }); assert.equal(result.identity.compiledRulebook?.rulebookId, "BTC_RULEBOOK"); assert.equal(result.parity.status, "NOT_REQUESTED"); });
test("rejects malformed requests before dependencies and leaves inputs unchanged", async () => { const h = harness(); const input = request({ asOf: new Date("invalid") }); const result = await h.service.execute(input); assert.equal(result.status, "FAILED"); assert.equal(result.stage, "REQUEST_VALIDATION"); assert.deepEqual(h.calls, { binding: 0, rulebook: 0, evidence: 0, attestation: 0, assembly: 0, compiled: 0, policy: 0, parity: 0 }); assert(Number.isNaN((input.asOf as Date).getTime())); });
test("skips USER templates and rejects incomplete parity input", async () => { let result = await harness().service.execute(request({ sourceTemplate: { ...sourceTemplate, scope: "USER" } })); assert.equal(result.status, "SKIPPED"); assert.equal(result.reasonCode, "TEMPLATE_NOT_ELIGIBLE"); result = await harness().service.execute(request({ legacyResult: {} })); assert.equal(result.status, "FAILED"); assert.equal(result.reasonCode, "INVALID_PARITY_INPUT_COMBINATION"); });
test("skips an absent exact binding and never continues", async () => { const h = harness({ executionBindingReader: { getExactForSourceTemplate: async () => { h.calls.binding++; return { found: false, code: "NOT_FOUND" }; } } }); const result = await h.service.execute(request()); assert.equal(result.status, "SKIPPED"); assert.equal(result.reasonCode, "NO_EXECUTION_BINDING"); assert.equal(h.calls.rulebook, 0); });
test("fails closed on binding persistence errors", async () => { const h = harness({ executionBindingReader: { getExactForSourceTemplate: async () => ({ found: false, code: "PERSISTENCE_ERROR" }) } }); const result = await h.service.execute(request()); assert.equal(result.status, "FAILED"); assert.equal(result.stage, "EXECUTION_BINDING_LOOKUP"); });
test("uses the binding exact rulebook identity and skips only NOT_FOUND", async () => { let received: unknown[] = []; const h = harness({ compiledRulebookReader: { getExact: async (...args: unknown[]) => { received = args; return { found: false, code: "NOT_FOUND" }; } } }); const result = await h.service.execute(request()); assert.deepEqual(received, ["BTC_RULEBOOK", 1]); assert.equal(result.status, "SKIPPED"); assert.equal(result.reasonCode, "EXACT_RULEBOOK_NOT_FOUND"); });
test("fails a request-binding-rulebook lineage mismatch", async () => { const wrong = { ...rulebook, source: { templateId: "OTHER", templateVersion: 1 } }; const h = harness({ compiledRulebookReader: { getExact: async () => ({ found: true, rulebook: wrong }) } }); const result = await h.service.execute(request()); assert.equal(result.status, "FAILED"); assert.equal(result.reasonCode, "RULEBOOK_IDENTITY_MISMATCH"); assert.equal(h.calls.evidence, 0); });
test("passes complete canonical history in order and omits missing attestations for A4", async () => { const second = { ...evidence, evidenceId: "EVIDENCE_2" }; let received: any; const h = harness({ evidenceReader: { read: async () => ({ history: [evidence, second], complete: true }) }, attestationReader: { getExactByEvidenceId: async (id: string) => id === evidence.evidenceId ? { found: true, attestation } : { found: false, code: "NOT_FOUND" } }, observationAssembler: { assemble: (value: any) => { received = value; return assembly(); } } }); await h.service.execute(request()); assert.deepEqual(received.evidence.map((item: any) => item.evidenceId), ["EVIDENCE_PRICE", "EVIDENCE_2"]); assert.deepEqual(received.attestations.map((item: any) => item.evidenceId), ["EVIDENCE_PRICE"]); });
test("fails incomplete Evidence history and attestation invariant violations at exact stages", async () => { let h = harness({ evidenceReader: { read: async () => ({ history: [], complete: false }) } }); let result = await h.service.execute(request()); assert.equal(result.status, "FAILED"); assert.equal(result.reasonCode, "INCOMPLETE_EVIDENCE_HISTORY"); h = harness({ attestationReader: { getExactByEvidenceId: async () => ({ found: false, code: "INVARIANT_VIOLATION" }) } }); result = await h.service.execute(request()); assert.equal(result.status, "FAILED"); if (result.status !== "FAILED") return; assert.equal(result.stage, "ATTESTATION_READ"); assert.equal(h.calls.assembly, 0); });
test("invokes A4 even with no Evidence and preserves its missing trace", async () => { const missing = assembly("NO_USABLE_EVIDENCE", []); const h = harness({ evidenceReader: { read: async () => ({ history: [], complete: true }) }, observationAssembler: { assemble: () => { h.calls.assembly++; return missing; } } }); const result = await h.service.execute(request()); assert.equal(h.calls.assembly, 1); assert.equal(result.status, "SKIPPED"); assert.equal(result.reasonCode, "NO_RELEVANT_EVIDENCE"); assert.deepEqual(result.assembly?.traces, missing.traces); });
test("allows PARTIAL assembly with observations and blocks invalid assembly", async () => { let h = harness({ observationAssembler: { assemble: () => assembly("PARTIAL") } }); let result = await h.service.execute(request()); assert.equal(result.status, "COMPLETED"); h = harness({ observationAssembler: { assemble: () => assembly("INVALID_EVIDENCE_SET", []) } }); result = await h.service.execute(request()); assert.equal(result.status, "FAILED"); assert.equal(h.calls.compiled, 0); });
test("preserves BLOCKED and INSUFFICIENT compiled outcomes but fails unrepresentable FAILED", async () => { for (const status of ["BLOCKED", "INSUFFICIENT_INPUT"]) { const h = harness({ compiledRulebookExecutor: { execute: () => compiled(status) } }); const result = await h.service.execute(request()); assert.equal(result.status, "COMPLETED"); assert.equal(result.compiledExecution?.status, status); } const h = harness({ compiledRulebookExecutor: { execute: () => compiled("FAILED") } }); const result = await h.service.execute(request()); assert.equal(result.status, "FAILED"); assert.equal(result.stage, "COMPILED_EXECUTION"); });
test("runs parity once with explicit numeric eligibility and keeps mismatch completed", async () => { const policy = { policyId: "PARITY", policyVersion: 1 }; const legacy = { score: 80, permission: "TAKE_TRADE", scoreStatus: "VALID", dataConfidence: "HIGH", reasonCodes: [], warnings: [], breakdown: {} }; const h = harness({ parityComparisonService: { compare: () => { h.calls.parity++; return { compared: true, result: { policy, overallComparability: "FULLY_COMPARABLE", numeric: { status: "MISMATCH" } } }; } } }); const result = await h.service.execute(request({ parityPolicy: policy, legacyResult: legacy, legacyNumericEligibility: { eligible: true, reasonCode: null } })); assert.equal(result.status, "COMPLETED"); assert.equal(result.parity.status, "COMPLETED"); assert.equal(h.calls.policy, 1); assert.equal(h.calls.parity, 1); });
test("contains invalid policy and comparison errors as nested parity unavailability", async () => { const parityInput = { parityPolicy: { policyId: "PARITY", policyVersion: 1 }, legacyResult: {}, legacyNumericEligibility: { eligible: true, reasonCode: null } }; let h = harness({ parityPolicyValidator: { validate: () => ({ valid: false, code: "INVALID_PARITY_POLICY" }) } }); let result = await h.service.execute(request(parityInput)); assert.equal(result.status, "COMPLETED"); assert.equal(result.parity.status, "UNAVAILABLE"); h = harness({ parityComparisonService: { compare: () => ({ compared: false, code: "INVALID_LEGACY_RESULT" }) } }); result = await h.service.execute(request(parityInput)); assert.equal(result.status, "COMPLETED"); assert.equal(result.parity.status, "UNAVAILABLE"); });
test("returns deterministic detached deeply frozen output with cloned Dates", async () => { const source = request(); const first = await harness().service.execute(source); const second = await harness().service.execute(request()); assert.deepEqual(first, second); assert(Object.isFrozen(first)); assert(Object.isFrozen(first.identity)); assert.notEqual(first.identity.asOf, source.asOf); if (first.status === "COMPLETED") { assert(Object.isFrozen(first.assembly)); assert.notEqual(first.compiledExecution.evaluatedAt, AS_OF); } assert.equal(AS_OF.toISOString(), "2026-08-05T10:00:00.000Z"); });
