import assert from "node:assert/strict";
import test from "node:test";
import { CompiledRulebookExecutionService } from "../../../src/services/compiled-rulebook-execution.service.js";

const policies = { aggregationPolicyId:"COMPILED_MEAN",aggregationPolicyVersion:1,normalizationPolicyId:"NORMALIZE",normalizationPolicyVersion:1,decisionBandPolicyId:"BANDS",decisionBandPolicyVersion:1 };
const binding = (order=0, requirementLevel:"MANDATORY"|"OPTIONAL"="MANDATORY", optionalBehavior:"PARTIAL"|"OMIT"|null=null):any => ({ bindingId:`ETF_${order}`,order,factor:{factorKey:"CRYPTO.ETF_NET_FLOW",factorVersion:1},subjectBinding:order===0?{type:"FIXED",subject:{type:"ASSET",key:"BTC"}}:{type:"TRADED_INSTRUMENT"},evaluator:{evaluatorId:"GENERIC_RELATIONSHIP_FACTOR_EVALUATOR",evaluatorVersion:1,configurationId:`ETF_${order}`,configurationVersion:1},relationshipType:"DIRECT",requirementLevel,optionalBehavior,weight:50,provider:{providerBindingId:`PROVIDER_${order}`,providerBindingVersion:1,resolutionPolicyId:"RESOLUTION",resolutionPolicyVersion:1},executionPolicies:{...policies} });
const rulebook = (bindings:any[]=[binding()]):any => ({identity:{rulebookId:"ETF_RULEBOOK",rulebookVersion:1},source:{templateId:"ETF_TEMPLATE",templateVersion:1},compilation:{compilerId:"YUDIJI_RULEBOOK_COMPILER",compilerVersion:1,compilationInputHash:"a".repeat(64),compiledAt:new Date("2026-08-01T00:00:00Z")},factorBindings:bindings,crossFactorPolicy:null,decisionPolicy:null});
const request:any={rulebook:{rulebookId:"ETF_RULEBOOK",rulebookVersion:1},asOf:new Date("2026-08-04T00:00:00Z"),subjectContext:{tradedInstrument:{type:"INSTRUMENT",key:"BTC_USD"},underlyingAsset:null},observations:[{}]};
const aggregation:any={policyId:"COMPILED_MEAN",policyVersion:1,strategy:"COMPILED_WEIGHTED_MEAN",partialWeightBehavior:"RETAIN_IN_DENOMINATOR",omittedWeightBehavior:"REMOVE_FROM_DENOMINATOR",compileEligible:true};
const normalization:any={compileEligible:true,definition:{normalizationPolicyId:"NORMALIZE",normalizationPolicyVersion:1,aggregationPolicyId:"LEGACY_AGG",aggregationPolicyVersion:1,factorKey:"CRYPTO.ETF_NET_FLOW",method:"PIECEWISE_LINEAR_ZERO_ANCHORED",sourceRange:{minimumPoints:-2,neutralPoints:0,maximumPoints:2},targetRange:{minimumScore:0,neutralScore:50,maximumScore:100},outOfRangePolicy:"FAIL",precisionPolicy:"PRESERVE_NATIVE"}};
const bands=[[-1,"STRONG_NEGATIVE",0,20],[2,"NEGATIVE",20,40],[3,"NEUTRAL",40,60],[4,"POSITIVE",60,80],[5,"STRONG_POSITIVE",80,100]].map((x,i)=>({order:i+1,label:x[1],minimumScore:x[2],maximumScore:x[3],minimumInclusive:true,maximumInclusive:i===4}));
const decision:any={compileEligible:true,definition:{decisionBandPolicyId:"BANDS",decisionBandPolicyVersion:1,normalizationPolicyId:"NORMALIZE",normalizationPolicyVersion:1,factorKey:"CRYPTO.ETF_NET_FLOW",normalizedRange:{minimumScore:0,maximumScore:100},bands}};
const trace=(b:any,state:"AVAILABLE"|"MISSING"|"INVALID"="AVAILABLE",score:number|null=50):any=>{const disposition=state==="AVAILABLE"?"INCLUDED":b.requirementLevel==="MANDATORY"?"BLOCKING":b.optionalBehavior==="PARTIAL"?"PARTIAL":"OMITTED";return {rulebook:{rulebookId:"ETF_RULEBOOK",rulebookVersion:1},bindingId:b.bindingId,bindingOrder:b.order,binding:structuredClone(b),lineage:{factor:{...b.factor},evaluator:{...b.evaluator},provider:{...b.provider},executionPolicies:{...b.executionPolicies}},resolvedSubject:state==="AVAILABLE"?{type:"ASSET",key:"BTC"}:null,providerAttestation:state==="AVAILABLE"?{providerBindingId:b.provider.providerBindingId,providerBindingVersion:1,resolutionPolicyId:"RESOLUTION",resolutionPolicyVersion:1,selectedProviderKey:"PRIMARY",resolutionOutcome:"RESOLVED"}:null,relationshipType:b.relationshipType,requirementLevel:b.requirementLevel,optionalBehavior:b.optionalBehavior,weight:b.weight,inputState:state,disposition,executionStatus:state==="AVAILABLE"?"EXECUTED":"NOT_EXECUTED",confidence:state==="AVAILABLE"?.8:null,freshness:null,observedAt:state==="AVAILABLE"?new Date("2026-08-03T00:00:00Z"):null,evaluatedAt:state==="AVAILABLE"?new Date(request.asOf):null,rawEvaluatorResult:state==="AVAILABLE"?{outcome:"NEUTRAL",contribution:{points:0,minimumPoints:-2,maximumPoints:2},reason:"x",diagnostics:{}}:null,bindingScore:state==="AVAILABLE"?score:null,preparationFailureCode:state==="AVAILABLE"?null:"OBSERVATION_NOT_FOUND",attestationFailureCode:null,executionFailureCode:null};};
const runtime=(states:any[]=[], calls:string[]=[])=>(new CompiledRulebookExecutionService({preparation:{assemble:({binding}:any)=>{calls.push(`prepare:${binding.order}`);return {resolved:false,code:"OBSERVATION_NOT_FOUND"} as any;}},bindings:{fromPreparation:({binding}:any)=>{calls.push(`execute:${binding.order}`);const s=states[binding.order]??["AVAILABLE",50];return {produced:true,result:trace(binding,s[0],s[1])};}},aggregationPolicies:{getExact:(id,v)=>{calls.push(`agg:${id}:${v}`);return aggregation;}},normalizationPolicies:{getExact:(id,v)=>{calls.push(`norm:${id}:${v}`);return normalization;}},decisionBandPolicies:{getExact:(id,v)=>{calls.push(`decision:${id}:${v}`);return decision;}}}));

test("executes ordered ETF bindings through aggregation normalization and decision",()=>{const calls:string[]=[];const rb=rulebook([binding(0),binding(1)]);const output=runtime([["AVAILABLE",100],["AVAILABLE",0]],calls).execute(rb,request);assert.equal(output.status,"COMPLETED");assert.equal(output.aggregateScore,50);assert.equal(output.normalizedScore,50);assert.equal(output.decisionBand?.label,"NEUTRAL");assert.deepEqual(output.bindingTraces.map(x=>x.bindingOrder),[0,1]);assert.deepEqual(calls,["agg:COMPILED_MEAN:1","norm:NORMALIZE:1","decision:BANDS:1","prepare:0","execute:0","prepare:1","execute:1"]);});
test("returns PARTIAL while retaining optional weight in denominator",()=>{const rb=rulebook([binding(0),binding(1,"OPTIONAL","PARTIAL")]);const o=runtime([["AVAILABLE",100],["MISSING",null]]).execute(rb,request);assert.equal(o.status,"PARTIAL");assert.equal(o.aggregateScore,50);assert.equal(o.counts.partialBindings,1);});
test("completes all traces before BLOCKED and returns INSUFFICIENT_INPUT for all omitted",()=>{let rb=rulebook([binding(0),binding(1)]);let o=runtime([["MISSING",null],["AVAILABLE",80]]).execute(rb,request);assert.equal(o.status,"BLOCKED");assert.equal(o.bindingTraces.length,2);assert.equal(o.normalization,null);rb=rulebook([binding(0,"OPTIONAL","OMIT"),binding(1,"OPTIONAL","OMIT")]);o=runtime([["MISSING",null],["INVALID",null]]).execute(rb,request);assert.equal(o.status,"INSUFFICIENT_INPUT");assert.equal(o.includedWeight,0);});
test("fails traversal invariant immediately and retains preceding traces",()=>{const rb=rulebook([binding(0),binding(1)]);const svc:any=runtime([["AVAILABLE",50],["AVAILABLE",50]]);svc.d.bindings.fromPreparation=({binding}:any)=>binding.order===0?{produced:true,result:trace(binding)}:{produced:false,code:"INVALID_RESOLVED_EXECUTION_INPUT"};const o=svc.execute(rb,request);assert.equal(o.status,"FAILED");assert.equal(o.failureCode,"BINDING_EXECUTION_INVARIANT_FAILED");assert.equal(o.failedBindingOrder,1);assert.equal(o.bindingTraces.length,1);assert.equal(o.aggregation,null);});
test("is deterministic deeply frozen and clones every date",()=>{const svc=runtime();const rb=rulebook();const a=svc.execute(rb,request),b=svc.execute(rb,request);assert.deepEqual(a,b);assert(Object.isFrozen(a)&&Object.isFrozen(a.bindingTraces)&&Object.isFrozen(a.decisionBand!));assert.notEqual(a.evaluatedAt,request.asOf);assert.notEqual(a.rulebook!.compilation.compiledAt,rb.compilation.compiledAt);});
test("rejects mixed factors and mixed policies before traversal and never calls latest",()=>{const calls:string[]=[];const mixed=rulebook([binding(0),{...binding(1),factor:{factorKey:"MARKET.PRICE",factorVersion:1}}]);assert.equal(runtime([],calls).execute(mixed,request).failureCode,"MIXED_FACTOR_RULEBOOK_NOT_SUPPORTED");assert.equal(calls.length,0);const p={...binding(1),executionPolicies:{...policies,normalizationPolicyVersion:2}};assert.equal(runtime([],calls).execute(rulebook([binding(0),p]),request).failureCode,"INCONSISTENT_NORMALIZATION_POLICY_LINEAGE");});
