import assert from "node:assert/strict";
import test from "node:test";
import { CompiledLegacyParityComparisonService } from "../../../src/services/compiled-legacy-parity-comparison.service.js";
import { CompiledLegacyParityPolicyService } from "../../../src/services/compiled-legacy-parity-policy.service.js";

const policy = (change: Record<string, unknown> = {}): any => ({
  policyId: "LEGACY_COMPILED_PARITY", policyVersion: 1,
  numeric: { enabled: true, legacySource: "SCORE", compiledSource: "NORMALIZED_SCORE", canonicalization: { method: "DECIMAL_PLACES", decimalPlaces: 2 }, comparison: "EXACT", forcedLegacyValueHandling: "REQUIRE_EXPLICIT_ELIGIBILITY" },
  semanticDimensions: [
    { dimensionId: "PERMISSION_TO_BAND", legacySource: "PERMISSION", compiledSource: "DECISION_BAND", mappings: [
      { legacyValue: "TAKE_TRADE", compiledValue: "STRONG_POSITIVE", outcome: "MATCH" },
      { legacyValue: "TAKE_TRADE", compiledValue: "NEGATIVE", outcome: "MISMATCH" },
    ] },
    { dimensionId: "STATUS_TO_EXECUTION", legacySource: "SCORE_STATUS", compiledSource: "EXECUTION_STATUS", mappings: [
      { legacyValue: "READY", compiledValue: "COMPLETED", outcome: "MATCH" },
      { legacyValue: "READY", compiledValue: "PARTIAL", outcome: "MISMATCH" },
    ] },
  ], ...change,
});
const legacy = (change: Record<string, unknown> = {}): any => ({ score: 75.004, permission: "TAKE_TRADE", scoreStatus: "READY", dataConfidence: "HIGH", reasonCodes: ["A"], warnings: ["W"], breakdown: { sectionResults: [{ sectionKey: "S", score: 75 }] }, ...change });
const compiled = (change: Record<string, unknown> = {}): any => ({ status: "COMPLETED", normalizedScore: 75.003, decisionBand: { label: "STRONG_POSITIVE" }, evaluatedAt: new Date("2026-08-04T00:00:00Z"), bindingTraces: [], counts: {}, policyLineage: {}, ...change });
const compare = (p = policy(), l = legacy(), c = compiled(), eligible = true) => new CompiledLegacyParityComparisonService().compare({ policy: p, legacy: l, compiled: c, legacyNumericEligibility: { eligible, reasonCode: eligible ? null : "LEGACY_FORCED_VALUE" } });

test("validates and deeply freezes a detached versioned policy", () => { const source = policy(); const result = new CompiledLegacyParityPolicyService().validate(source); assert(result.valid); if (!result.valid) return; assert.deepEqual(result.policy, source); assert.notEqual(result.policy, source); assert(Object.isFrozen(result) && Object.isFrozen(result.policy.numeric) && Object.isFrozen(result.policy.semanticDimensions[0]!.mappings)); });
test("rejects invalid identity version numeric configuration and comparison modes", () => { const service = new CompiledLegacyParityPolicyService(); assert.deepEqual(service.validate(policy({ policyId: "" })), { valid: false, code: "INVALID_POLICY_ID" }); assert.deepEqual(service.validate(policy({ policyVersion: 0 })), { valid: false, code: "INVALID_POLICY_VERSION" }); assert.deepEqual(service.validate(policy({ numeric: { ...policy().numeric, canonicalization: { method: "DECIMAL_PLACES", decimalPlaces: -1 } } })), { valid: false, code: "INVALID_NUMERIC_CANONICALIZATION" }); assert.deepEqual(service.validate(policy({ numeric: { ...policy().numeric, comparison: "FUZZY" } })), { valid: false, code: "UNSUPPORTED_NUMERIC_COMPARISON" }); });
test("rejects duplicate and contradictory semantic mappings", () => { const base = policy().semanticDimensions[0]; const duplicate = { ...base, mappings: [...base.mappings, { ...base.mappings[0] }] }; const contradictory = { ...base, mappings: [...base.mappings, { ...base.mappings[0], outcome: "MISMATCH" }] }; assert.equal((new CompiledLegacyParityPolicyService().validate(policy({ semanticDimensions: [duplicate] })) as any).code, "DUPLICATE_SEMANTIC_MAPPING"); assert.equal((new CompiledLegacyParityPolicyService().validate(policy({ semanticDimensions: [contradictory] })) as any).code, "CONTRADICTORY_SEMANTIC_MAPPING"); });
test("matches and mismatches exact canonical decimals while preserving originals", () => { let result = compare(); assert(result.compared); if (!result.compared) return; assert.equal(result.result.numeric.status, "MATCH"); assert.equal(result.result.numeric.legacyOriginal, 75.004); assert.equal(result.result.numeric.compiledOriginal, 75.003); assert.equal(result.result.numeric.legacyCanonical, "75.00"); assert.equal(result.result.numeric.compiledCanonical, "75.00"); result = compare(policy(), legacy({ score: 75.006 }), compiled({ normalizedScore: 75.004 })); assert(result.compared); if (result.compared) assert.equal(result.result.numeric.status, "MISMATCH"); });
test("uses no epsilon or fuzzy equality", () => { const result = compare(policy({ numeric: { ...policy().numeric, canonicalization: { method: "DECIMAL_PLACES", decimalPlaces: 6 } } }), legacy({ score: 1 }), compiled({ normalizedScore: 1.0000001 })); assert(result.compared); if (result.compared) assert.equal(result.result.numeric.status, "MATCH"); const exact = compare(policy({ numeric: { ...policy().numeric, canonicalization: { method: "DECIMAL_PLACES", decimalPlaces: 7 } } }), legacy({ score: 1 }), compiled({ normalizedScore: 1.0000001 })); assert(exact.compared); if (exact.compared) assert.equal(exact.result.numeric.status, "MISMATCH"); });
test("reports disabled missing and forced numeric comparison as unavailable", () => { for (const result of [compare(policy({ numeric: { ...policy().numeric, enabled: false } })), compare(policy(), legacy(), compiled({ normalizedScore: null })), compare(policy(), legacy(), compiled(), false)]) { assert(result.compared); if (result.compared) assert.equal(result.result.numeric.status, "UNAVAILABLE"); } });
test("rejects non-finite legacy and compiled numbers", () => { assert.deepEqual(compare(policy(), legacy({ score: NaN })), { compared: false, code: "INVALID_LEGACY_RESULT" }); assert.deepEqual(compare(policy(), legacy(), compiled({ normalizedScore: Infinity })), { compared: false, code: "INVALID_COMPILED_RESULT" }); });
test("compares permission and status independently and preserves valid mismatches", () => { const result = compare(policy(), legacy(), compiled({ status: "PARTIAL", decisionBand: { label: "STRONG_POSITIVE" } })); assert(result.compared); if (!result.compared) return; assert.deepEqual(result.result.semanticDimensions.map(x => [x.dimensionId, x.status]), [["PERMISSION_TO_BAND", "MATCH"], ["STATUS_TO_EXECUTION", "MISMATCH"]]); assert.equal(result.result.overallComparability, "FULLY_COMPARABLE"); });
test("unknown semantic pairs are unmappable and never matches", () => { const result = compare(policy(), legacy({ permission: "WAIT" }), compiled()); assert(result.compared); if (!result.compared) return; assert.equal(result.result.semanticDimensions[0]!.status, "UNMAPPABLE"); assert.equal(result.result.overallComparability, "PARTIALLY_COMPARABLE"); });
test("derives fully partially and not comparable without treating unavailable as mismatch", () => { const full = compare(); assert(full.compared && full.result.overallComparability === "FULLY_COMPARABLE"); const partial = compare(policy(), legacy({ permission: "WAIT" }), compiled()); assert(partial.compared && partial.result.overallComparability === "PARTIALLY_COMPARABLE"); const none = compare(policy({ numeric: { ...policy().numeric, enabled: false } }), legacy({ permission: "WAIT", scoreStatus: "UNAVAILABLE" }), compiled({ status: "BLOCKED", decisionBand: null })); assert(none.compared && none.result.overallComparability === "NOT_COMPARABLE"); if (none.compared) assert(none.result.semanticDimensions.every(x => x.status !== "MISMATCH")); });
test("lists diagnostic-only fields without fake equality", () => { const result = compare(); assert(result.compared); if (!result.compared) return; const fields = result.result.nonComparableDiagnostics.map(x => x.field); for (const field of ["REASON_CODE_ORDER", "WARNING_ORDER", "BREAKDOWN_HIERARCHY", "PROVIDER_LINEAGE", "POLICY_LINEAGE", "GENERATED_IDS", "PERSISTENCE_TIMESTAMPS", "COMPILED_COUNTS", "COMPILED_BINDING_TRACES", "LEGACY_SECTION_SCORES"]) assert(fields.includes(field as any)); assert(result.result.nonComparableDiagnostics.every(x => x.classification === "DIAGNOSTIC_ONLY")); });
test("is deterministic detached deeply frozen and clones included dates without mutation", () => { const p=policy(),l=legacy(),c=compiled(); const service=new CompiledLegacyParityComparisonService(); const a=service.compare({policy:p,legacy:l,compiled:c,legacyNumericEligibility:{eligible:true,reasonCode:null}}),b=service.compare({policy:p,legacy:l,compiled:c,legacyNumericEligibility:{eligible:true,reasonCode:null}}); assert.deepEqual(a,b); assert(a.compared&&b.compared); if(!a.compared||!b.compared)return; assert(Object.isFrozen(a.result)&&Object.isFrozen(a.result.semanticDimensions)&&Object.isFrozen(a.result.compiledProjection)); assert.notEqual(a.result.compiledProjection.evaluatedAt,c.evaluatedAt); assert.deepEqual(p,policy()); assert.deepEqual(l,legacy()); assert.deepEqual(c,compiled()); });
