import test from "node:test"; import assert from "node:assert/strict";
import { KnowledgeDocumentAdmissionService } from "../../../src/services/knowledge-document-admission.service.js";
import { documentMaterial } from "../../fixtures/platform-knowledge.fixture.js";
const service = new KnowledgeDocumentAdmissionService();
test("admits deterministic SYSTEM platform knowledge and freezes output", () => { const input = documentMaterial(); const a = service.admit({ document: input }); const b = service.admit({ document: structuredClone(input) }); assert.deepEqual(a, b); assert.equal(a.admitted, true); if (a.admitted) { assert.match(a.document.contentDigest, /^[a-f0-9]{64}$/); assert.ok(Object.isFrozen(a.document.blocks)); } assert.equal(Object.isFrozen(input), false); });
test("rejects unsupported corpora, ownership, and trust", () => { for (const patch of [{ corpus: "MARKET_RESEARCH" }, { corpus: "USER_PRIVATE_DOCUMENTS" }, { ownership: { ownerType: "USER", ownerId: "USER_1" } }, { trustLevel: "UNVERIFIED" }] as const) { const result = service.admit({ document: { ...documentMaterial(), ...patch } as any }); assert.equal(result.admitted, false); } });
test("rejects parser, effective-time, supersession and bounds failures", () => { assert.deepEqual(service.admit({ document: { ...documentMaterial(), parser: { parserId: "bad parser", parserVersion: 1 } } }), { admitted: false, code: "INVALID_PARSER" }); assert.deepEqual(service.admit({ document: { ...documentMaterial(), effectiveFrom: new Date("2026-02-01"), effectiveUntil: new Date("2026-01-01") } }), { admitted: false, code: "INVALID_EFFECTIVE_TIME" }); const d = documentMaterial(); assert.deepEqual(service.admit({ document: { ...d, supersedes: d.identity } }), { admitted: false, code: "INVALID_SUPERSESSION" }); assert.deepEqual(service.admit({ document: { ...d, title: "x".repeat(241) } }), { admitted: false, code: "INVALID_BLOCKS" }); });
test("digest changes with content, parser, trust, source, and span but ignores createdAt", () => { const base = service.admit({ document: documentMaterial() }); assert.equal(base.admitted, true); if (!base.admitted) return; const variants = [ { ...documentMaterial(), parser: { parserId: "MANUAL_NORMALIZER", parserVersion: 2 } }, { ...documentMaterial(), trustLevel: "AUTHORITATIVE" as const }, { ...documentMaterial(), source: { sourceType: "MANUAL_NORMALIZED_FIXTURE", sourceIdentity: "OTHER" } }, { ...documentMaterial(), blocks: documentMaterial().blocks.map((b, i) => i ? b : { ...b, sourceSpan: { sectionPath: ["YUDIJI"], paragraphStart: 2, paragraphEnd: 2 } }) }, { ...documentMaterial(), blocks: documentMaterial().blocks.map((b, i) => i ? b : { ...b, text: `${b.text} changed` }) } ]; for (const v of variants) { const r = service.admit({ document: v }); assert.equal(r.admitted, true); if (r.admitted) assert.notEqual(r.document.contentDigest, base.document.contentDigest); } });
test("expected digest mismatch fails closed", () => assert.deepEqual(service.admit({ document: documentMaterial(), expectedContentDigest: "0".repeat(64) }), { admitted: false, code: "DIGEST_MISMATCH" }));

