import assert from "node:assert/strict";
import test from "node:test";
import { KnowledgeRetrievalPolicyRegistry } from "../../../src/registries/knowledge-retrieval-policy.registry.js";
import { KnowledgeQueryTextService } from "../../../src/services/knowledge-query-text.service.js";
import { KnowledgeRetrievalRerankingService } from "../../../src/services/knowledge-retrieval-reranking.service.js";
import { KnowledgeCitationHandleService } from "../../../src/services/knowledge-citation-handle.service.js";
import { KnowledgeCitationValidationService } from "../../../src/services/knowledge-citation-validation.service.js";
import { KnowledgeContextAssemblyService } from "../../../src/services/knowledge-context-assembly.service.js";
import type { KnowledgeRetrievalPolicy, KnowledgeRetrievalRequest, ValidatedKnowledgeRetrievalCandidate } from "../../../src/types/knowledge-retrieval.types.js";
import type { KnowledgeEmbeddingSchemaDefinition } from "../../../src/types/knowledge-embedding.types.js";

const policy:KnowledgeRetrievalPolicy={policyId:"PLATFORM_RETRIEVAL",policyVersion:1,allowedCorpora:["PLATFORM_KNOWLEDGE"],allowedTrustLevels:["AUTHORITATIVE","APPROVED_GUIDANCE","EXPLANATORY"],maxQueryCharacters:1000,maxQueryConcepts:10,maxEligibleDocuments:20,vectorCandidateLimit:10,lexicalCandidateLimit:10,finalTopK:3,vectorWeight:1,lexicalWeight:1,metadataMatchWeight:.2,trustWeight:.1,vectorScoreRange:{minimum:-1,maximum:1,clamp:true},lexicalScoreRange:{minimum:0,maximum:1,clamp:true},trustScores:{AUTHORITATIVE:1,APPROVED_GUIDANCE:.5,EXPLANATORY:0},maxChunksPerDocument:2,maxParentChunks:1,maxSiblingChunks:1,contextCharacterBudget:1000,maxPassageCharacters:500,includeVectorSearch:true,includeLexicalSearch:true,includeParentContext:false,includeSiblingContext:false,excludeSupersededMembers:true,vectorFailureFallback:"LEXICAL_ONLY",lexicalFailureFallback:"VECTOR_ONLY",noContextBehavior:"NO_CONTEXT"};
const schema:KnowledgeEmbeddingSchemaDefinition={embeddingSchemaId:"TEST_SCHEMA",embeddingSchemaVersion:1,providerId:"TEST_PROVIDER",providerVersion:1,modelId:"TEST_MODEL",modelVersion:"1",vectorDimension:4,similarityMetric:"COSINE",normalizationStrategyId:"TEST_NO_NORMALIZATION",normalizationStrategyVersion:1,embeddingTextProjectorId:"PROJECTOR",embeddingTextProjectorVersion:1,allowedCorpora:["PLATFORM_KNOWLEDGE"],allowedTrustLevels:["AUTHORITATIVE"],allowedPurposes:["RETRIEVAL_DOCUMENT","RETRIEVAL_QUERY"],activeForGeneration:true};
const request:KnowledgeRetrievalRequest={requestId:"REQUEST",requestVersion:1,query:{text:"How does ETF net flow work?",concepts:["ETF flow"]},scope:{corpus:"PLATFORM_KNOWLEDGE",trustLevels:["AUTHORITATIVE"]},filters:{factorKeys:["CRYPTO.ETF_NET_FLOW"]},embeddingSchema:{embeddingSchemaId:"TEST_SCHEMA",embeddingSchemaVersion:1},vectorIndex:{indexId:"TEST_INDEX",indexVersion:1},retrievalPolicy:{policyId:policy.policyId,policyVersion:1},eligibleDocuments:[{documentId:"DOC",documentVersion:1}],asOf:new Date("2026-01-01T00:00:00Z")};
const document:any={identity:{documentId:"DOC",documentVersion:1},corpus:"PLATFORM_KNOWLEDGE",documentType:"FACTOR_DOCUMENTATION",title:"ETF flow",ownership:{ownerType:"SYSTEM"},source:{sourceType:"INTERNAL",sourceIdentity:"ADR-TEST"},trustLevel:"AUTHORITATIVE",parser:{parserId:"TEST",parserVersion:1},admissionPolicy:{policyId:"TEST",policyVersion:1},blocks:[],contentDigest:"d".repeat(64),createdAt:new Date("2025-01-01T00:00:00Z")};
const chunk:any={identity:{chunkId:"CHUNK",chunkVersion:1},documentIdentity:document.identity,strategy:{strategyId:"TEST",strategyVersion:1},chunkType:"IDENTITY_AND_MEANING",ordinal:0,content:"ETF net flow measures net fund movement.",sourceSpan:{sectionPath:["Meaning"]},metadata:{factors:[{factorKey:"CRYPTO.ETF_NET_FLOW",factorVersion:1}],relationshipTypes:["DIRECT"],subjectTypes:[],markets:[],topics:["ETF"],validationCodes:[]},contentDigest:"c".repeat(64),createdAt:new Date("2025-01-01T00:00:00Z")};
const candidate:ValidatedKnowledgeRetrievalCandidate={candidate:{documentIdentity:document.identity,chunkIdentity:chunk.identity,sources:[{type:"VECTOR",rawScore:.8,indexEntryId:"ENTRY",indexEntryVersion:1,embeddingIdentity:{embeddingId:"EMBED",embeddingVersion:1},indexedChunkDigest:chunk.contentDigest,indexedVectorDigest:"v".repeat(64)},{type:"LEXICAL",rawScore:.5}],matchedFilters:["factor"]},document,chunk,verifiedChunks:[chunk],chunkSetIdentity:{chunkSetId:"SET",chunkSetVersion:1}};

test("retrieval policy registry resolves exact immutable versions and has no latest",()=>{const registry=new KnowledgeRetrievalPolicyRegistry([policy]);const value=registry.getExact(policy.policyId,1)!;assert.deepEqual(value,policy);assert.ok(Object.isFrozen(value));assert.equal("getLatest" in registry,false);assert.equal(registry.getExact(policy.policyId,2),null);});
test("retrieval policy rejects invalid and duplicate definitions",()=>{assert.throws(()=>new KnowledgeRetrievalPolicyRegistry([{...policy,vectorWeight:Number.NaN}]));assert.throws(()=>new KnowledgeRetrievalPolicyRegistry([policy,policy]),/DUPLICATE/);});
test("query projection is deterministic, bounded and excludes asOf",()=>{const service=new KnowledgeQueryTextService();const a=service.project(request,schema)!;const b=service.project({...request,asOf:new Date("2030-01-01T00:00:00Z")},schema)!;assert.deepEqual(a,b);assert.match(a.text,/ETF net flow/);assert.match(a.text,/CRYPTO.ETF_NET_FLOW/);assert.doesNotMatch(a.text,/2026|2030/);assert.ok(Object.isFrozen(a));});
test("hybrid reranking preserves normalized components and is input-order independent",()=>{const service=new KnowledgeRetrievalRerankingService();const ranked=service.rank([candidate],policy);assert.equal(ranked[0]?.ranking.vectorScore,.9);assert.equal(ranked[0]?.ranking.lexicalScore,.5);assert.ok(Number.isFinite(ranked[0]!.ranking.finalScore));assert.deepEqual(ranked,service.rank([candidate],policy));assert.ok(Object.isFrozen(ranked));});
test("citation handle changes with material lineage",()=>{const service=new KnowledgeCitationHandleService();const base:any={contextId:"CTX",contextVersion:1,requestId:"REQUEST",requestVersion:1,policy:request.retrievalPolicy,documentIdentity:document.identity,documentDigest:document.contentDigest,chunkSetIdentity:{chunkSetId:"SET",chunkSetVersion:1},chunkIdentity:chunk.identity,chunkDigest:chunk.contentDigest,sourceIdentity:"ADR-TEST",sourceSpan:chunk.sourceSpan,corpus:"PLATFORM_KNOWLEDGE",trustLevel:"AUTHORITATIVE"};assert.equal(service.create(base),service.create(base));assert.notEqual(service.create(base),service.create({...base,chunkDigest:"x".repeat(64)}));});
test("context assembly applies citations, untrusted labels and character budget",()=>{const ranked=new KnowledgeRetrievalRerankingService().rank([candidate],policy);const query=new KnowledgeQueryTextService().project(request,schema)!;const context=new KnowledgeContextAssemblyService().assemble({contextId:"CTX",contextVersion:1,request,policy,query,candidates:ranked,excluded:[],partial:false})!;assert.equal(context.status,"COMPLETED");assert.equal(context.passages[0]?.securityLabel,"UNTRUSTED_RETRIEVED_CONTENT");assert.equal(context.budget.used,chunk.content.length);assert.equal("vector" in context.passages[0]!,false);assert.ok(Object.isFrozen(context.passages));});
test("citation validation accepts only selected exact handles and rejects duplicates",()=>{const ranked=new KnowledgeRetrievalRerankingService().rank([candidate],policy);const query=new KnowledgeQueryTextService().project(request,schema)!;const context=new KnowledgeContextAssemblyService().assemble({contextId:"CTX",contextVersion:1,request,policy,query,candidates:ranked,excluded:[],partial:false})!;const handle=context.passages[0]!.citationHandle;assert.deepEqual(new KnowledgeCitationValidationService().validate([handle,handle,"forged"],context).map(x=>x.status),["VALID","DUPLICATE_HANDLE","UNKNOWN_HANDLE"]);});
test("oversized complete chunks are excluded rather than truncated",()=>{const small={...policy,maxPassageCharacters:5,contextCharacterBudget:10};const ranked=new KnowledgeRetrievalRerankingService().rank([candidate],small);const query=new KnowledgeQueryTextService().project(request,schema)!;const context=new KnowledgeContextAssemblyService().assemble({contextId:"CTX",contextVersion:1,request,policy:small,query,candidates:ranked,excluded:[],partial:false})!;assert.equal(context.status,"NO_CONTEXT");assert.equal(context.passages.length,0);assert.equal(context.excludedCandidates[0]?.code,"CONTEXT_BUDGET_EXCLUDED");});
test("parent and sibling expansion is exact, bounded and non-recursive",()=>{const parent={...chunk,identity:{chunkId:"PARENT",chunkVersion:1},ordinal:0,content:"Parent"};const primary={...chunk,parent:parent.identity,ordinal:1};const sibling={...chunk,identity:{chunkId:"SIBLING",chunkVersion:1},ordinal:2,content:"Sibling"};const expanded={...candidate,chunk:primary,verifiedChunks:[parent,primary,sibling]};const expanding={...policy,includeParentContext:true,includeSiblingContext:true,maxParentChunks:1,maxSiblingChunks:1,maxChunksPerDocument:3};const ranked=new KnowledgeRetrievalRerankingService().rank([expanded],expanding);const query=new KnowledgeQueryTextService().project(request,schema)!;const context=new KnowledgeContextAssemblyService().assemble({contextId:"CTX",contextVersion:1,request,policy:expanding,query,candidates:ranked,excluded:[],partial:false})!;assert.deepEqual(context.passages.map(x=>x.role),["PRIMARY_MATCH","PARENT_CONTEXT","SIBLING_CONTEXT"]);assert.equal(new Set(context.passages.map(x=>x.chunkId)).size,3);});
