import assert from "node:assert/strict";
import test from "node:test";
import { KnowledgeEmbeddingSchemaRegistry } from "../../../src/registries/knowledge-embedding-schema.registry.js";
import { KnowledgeRetrievalPolicyRegistry } from "../../../src/registries/knowledge-retrieval-policy.registry.js";
import { KnowledgeVectorIndexDefinitionRegistry } from "../../../src/registries/knowledge-vector-index-definition.registry.js";
import { KnowledgeRetrievalService } from "../../../src/services/knowledge-retrieval.service.js";
import { KnowledgeEmbeddingNormalizationRegistry } from "../../../src/registries/knowledge-embedding-normalization.registry.js";
import { KnowledgeEmbeddingNormalizationService } from "../../../src/services/knowledge-embedding-normalization.service.js";
import type { KnowledgeRetrievalPolicy, KnowledgeRetrievalRequest, ValidatedKnowledgeRetrievalCandidate } from "../../../src/types/knowledge-retrieval.types.js";
const policy:KnowledgeRetrievalPolicy={policyId:"PLATFORM_RETRIEVAL",policyVersion:1,allowedCorpora:["PLATFORM_KNOWLEDGE"],allowedTrustLevels:["AUTHORITATIVE"],maxQueryCharacters:1000,maxQueryConcepts:10,maxEligibleDocuments:10,vectorCandidateLimit:5,lexicalCandidateLimit:5,finalTopK:2,vectorWeight:1,lexicalWeight:1,metadataMatchWeight:0,trustWeight:0,vectorScoreRange:{minimum:-1,maximum:1,clamp:true},lexicalScoreRange:{minimum:0,maximum:1,clamp:true},trustScores:{AUTHORITATIVE:1},maxChunksPerDocument:2,maxParentChunks:0,maxSiblingChunks:0,contextCharacterBudget:1000,maxPassageCharacters:500,includeVectorSearch:true,includeLexicalSearch:true,includeParentContext:false,includeSiblingContext:false,excludeSupersededMembers:true,vectorFailureFallback:"LEXICAL_ONLY",lexicalFailureFallback:"VECTOR_ONLY",noContextBehavior:"NO_CONTEXT"};
const schema:any={embeddingSchemaId:"TEST_SCHEMA",embeddingSchemaVersion:1,providerId:"TEST_PROVIDER",providerVersion:1,modelId:"TEST_MODEL",modelVersion:"1",vectorDimension:4,similarityMetric:"COSINE",normalizationStrategyId:"TEST_NO_NORMALIZATION",normalizationStrategyVersion:1,embeddingTextProjectorId:"PROJECTOR",embeddingTextProjectorVersion:1,allowedCorpora:["PLATFORM_KNOWLEDGE"],allowedTrustLevels:["AUTHORITATIVE"],allowedPurposes:["RETRIEVAL_DOCUMENT","RETRIEVAL_QUERY"],activeForGeneration:true};
const index:any={indexId:"TEST_INDEX",indexVersion:1,indexSchemaId:"INDEX_SCHEMA",indexSchemaVersion:1,namespace:"PLATFORM.TEST",corpus:"PLATFORM_KNOWLEDGE",allowedTrustLevels:["AUTHORITATIVE"],embeddingSchema:{embeddingSchemaId:"TEST_SCHEMA",embeddingSchemaVersion:1},vectorDimension:4,similarityMetric:"COSINE",metadataSchemaId:"METADATA",metadataSchemaVersion:1,writePolicyId:"WRITE",writePolicyVersion:1,retrievalEligible:true};
const request:KnowledgeRetrievalRequest={requestId:"REQUEST",requestVersion:1,query:{text:"ETF flow",concepts:[]},scope:{corpus:"PLATFORM_KNOWLEDGE",trustLevels:["AUTHORITATIVE"]},embeddingSchema:index.embeddingSchema,vectorIndex:{indexId:index.indexId,indexVersion:1},retrievalPolicy:{policyId:policy.policyId,policyVersion:1},eligibleDocuments:[{documentId:"DOC",documentVersion:1}],asOf:new Date("2026-01-01T00:00:00Z")};
const document:any={identity:request.eligibleDocuments[0],corpus:"PLATFORM_KNOWLEDGE",documentType:"FACTOR_DOCUMENTATION",title:"ETF",ownership:{ownerType:"SYSTEM"},source:{sourceType:"INTERNAL",sourceIdentity:"SOURCE"},trustLevel:"AUTHORITATIVE",parser:{parserId:"TEST",parserVersion:1},admissionPolicy:{policyId:"TEST",policyVersion:1},blocks:[],contentDigest:"d".repeat(64),createdAt:new Date("2025-01-01T00:00:00Z")};
const chunk:any={identity:{chunkId:"CHUNK",chunkVersion:1},documentIdentity:document.identity,strategy:{strategyId:"S",strategyVersion:1},chunkType:"IDENTITY_AND_MEANING",ordinal:0,content:"ETF flow guidance",sourceSpan:{sectionPath:["ETF"]},metadata:{factors:[],relationshipTypes:[],subjectTypes:[],markets:[],topics:[],validationCodes:[]},contentDigest:"c".repeat(64),createdAt:new Date("2025-01-01T00:00:00Z")};
const valid:ValidatedKnowledgeRetrievalCandidate={candidate:{documentIdentity:document.identity,chunkIdentity:chunk.identity,sources:[{type:"VECTOR",rawScore:.8,providerOrdinal:0,indexEntryId:"ENTRY",indexEntryVersion:1,index:{indexId:index.indexId,indexVersion:1},namespace:index.namespace,embeddingIdentity:{embeddingId:"E",embeddingVersion:1},chunkSetIdentity:{chunkSetId:"SET",chunkSetVersion:1},indexedChunkDigest:chunk.contentDigest,indexedVectorDigest:"v".repeat(64)},{type:"LEXICAL",rawScore:.8}],matchedFilters:[]},document,chunk,verifiedChunks:[chunk],chunkSetIdentity:{chunkSetId:"SET",chunkSetVersion:1}};
const deps=(vectorStatus="COMPLETED")=>{const calls={embed:0,vector:0,lexical:0};let embeddingRequest:any=null;let vectorRequest:any=null;const service=new KnowledgeRetrievalService(new KnowledgeRetrievalPolicyRegistry([policy]),new KnowledgeEmbeddingSchemaRegistry([schema]),new KnowledgeVectorIndexDefinitionRegistry([index],new KnowledgeEmbeddingSchemaRegistry([schema])),{embed:async(request:any)=>{calls.embed++;embeddingRequest=request;return{status:"COMPLETED",providerId:"TEST_PROVIDER",providerVersion:1,modelId:"TEST_MODEL",modelVersion:"1",vectors:[{inputId:"RETRIEVAL_QUERY",values:[1,0,0,0]}]};}},{search:async(searchRequest:any)=>{calls.vector++;vectorRequest=searchRequest;return vectorStatus==="COMPLETED"?{status:"COMPLETED",candidates:[{indexEntryId:"ENTRY",indexEntryVersion:1,index:{indexId:index.indexId,indexVersion:1},namespace:index.namespace,embeddingIdentity:{embeddingId:"E",embeddingVersion:1},documentIdentity:document.identity,chunkSetIdentity:{chunkSetId:"SET",chunkSetVersion:1},chunkIdentity:chunk.identity,providerScore:.8,providerOrdinal:0,chunkDigest:chunk.contentDigest,vectorDigest:"v".repeat(64)}]}:{status:"SEARCH_FAILED",candidates:[],failureCode:"TEST"};}} as any,{search:async()=>{calls.lexical++;return{status:"COMPLETED",candidates:[{documentIdentity:document.identity,chunkIdentity:chunk.identity,score:.8,matchedFilters:[]}]};}},undefined as any,{validate:async()=>({valid:[valid],excluded:[]})} as any,undefined as any,undefined as any,{findExact:async()=>({found:true,document})} as any);return{service,calls,get embeddingRequest(){return embeddingRequest;},get vectorRequest(){return vectorRequest;}};};
test("standalone retrieval remains disabled without provider or search calls",async()=>{const {service,calls}=deps();const result=await service.retrieve(request,{enabled:false,contextId:"CTX",contextVersion:1});assert.equal(result.status,"FEATURE_DISABLED");assert.deepEqual(calls,{embed:0,vector:0,lexical:0});});
test("hybrid retrieval supplies query purpose, canonical vector and cloned exact asOf",async()=>{const dependencies=deps();const originalTime=request.asOf.getTime();const result=await dependencies.service.retrieve(request,{enabled:true,contextId:"CTX",contextVersion:1});assert.equal(result.status,"COMPLETED");assert.deepEqual(dependencies.calls,{embed:1,vector:1,lexical:1});assert.equal(dependencies.embeddingRequest.purpose,"RETRIEVAL_QUERY");assert.deepEqual(dependencies.vectorRequest.queryVector,[1,0,0,0]);assert.equal(dependencies.vectorRequest.asOf.getTime(),originalTime);assert.notEqual(dependencies.vectorRequest.asOf,request.asOf);assert.equal(request.asOf.getTime(),originalTime);assert.ok(Object.isFrozen(dependencies.vectorRequest));assert.ok(Object.isFrozen(dependencies.vectorRequest.asOf));assert.equal(result.context?.passages.length,1);assert.equal(result.context?.passages[0]?.securityLabel,"UNTRUSTED_RETRIEVED_CONTENT");assert.ok(Object.isFrozen(result));});

test("retrieval rejects a schema that disallows query purpose before provider invocation",async()=>{const dependencies=deps();const restricted={...schema,allowedPurposes:["RETRIEVAL_DOCUMENT"]};const service=new KnowledgeRetrievalService(new KnowledgeRetrievalPolicyRegistry([policy]),new KnowledgeEmbeddingSchemaRegistry([restricted]),new KnowledgeVectorIndexDefinitionRegistry([index],new KnowledgeEmbeddingSchemaRegistry([restricted])),{embed:async()=>{dependencies.calls.embed++;throw new Error("must not call");}} as any,{} as any,{} as any,undefined as any,undefined as any,undefined as any,undefined as any,{findExact:async()=>({found:true,document})} as any);const result=await service.retrieve(request,{enabled:true,contextId:"CTX",contextVersion:1});assert.equal(result.status,"QUERY_EMBEDDING_FAILED");assert.equal(result.failureCode,"PURPOSE_NOT_ALLOWED");assert.equal(dependencies.calls.embed,0);});

test("retrieval normalizes a raw query vector before search and stops on zero magnitude",async()=>{const definition:any={normalizationStrategyId:"TEST_L2",normalizationStrategyVersion:1,algorithm:"L2_UNIT_VECTOR",inputDimension:4,zeroMagnitudeBehavior:"FAIL",numericPolicy:{requireFiniteInput:true,requireFiniteOutput:true,rounding:"NONE",clamping:"NONE"},validationPolicy:{unitMagnitudeTolerance:1e-12}};const authority=new KnowledgeEmbeddingNormalizationRegistry([definition]);const l2Schema={...schema,normalizationStrategyId:"TEST_L2"};const schemas=new KnowledgeEmbeddingSchemaRegistry([l2Schema],authority);const indexes=new KnowledgeVectorIndexDefinitionRegistry([index],schemas);let raw=[3,4,0,0],searched:any=null,searchCalls=0;const service=new KnowledgeRetrievalService(new KnowledgeRetrievalPolicyRegistry([policy]),schemas,indexes,{embed:async()=>({status:"COMPLETED",providerId:"TEST_PROVIDER",providerVersion:1,modelId:"TEST_MODEL",modelVersion:"1",vectors:[{inputId:"RETRIEVAL_QUERY",values:raw}]})},{search:async(r:any)=>{searchCalls++;searched=r.queryVector;return{status:"NO_CANDIDATES",candidates:[]};}} as any,{search:async()=>({status:"NO_CANDIDATES",candidates:[]})} as any,undefined as any,undefined as any,undefined as any,undefined as any,{findExact:async()=>({found:true,document})} as any,new KnowledgeEmbeddingNormalizationService(authority));let result=await service.retrieve(request,{enabled:true,contextId:"CTX",contextVersion:1});assert.equal(result.status,"NO_CONTEXT");assert.deepEqual(searched,[0.6,0.8,0,0]);assert.notEqual(searched,raw);raw=[0,0,0,0];result=await service.retrieve(request,{enabled:true,contextId:"CTX",contextVersion:1});assert.equal(result.status,"QUERY_EMBEDDING_FAILED");assert.equal(result.failureCode,"VECTOR_MAGNITUDE_ZERO");assert.equal(searchCalls,1);});
test("explicit lexical fallback returns PARTIAL and preserves vector failure",async()=>{const {service,calls}=deps("SEARCH_FAILED");const result=await service.retrieve(request,{enabled:true,contextId:"CTX",contextVersion:1});assert.equal(result.status,"PARTIAL");assert.deepEqual(calls,{embed:1,vector:1,lexical:1});});
test("request requires explicit unique eligible document versions",async()=>{const {service,calls}=deps();const result=await service.retrieve({...request,eligibleDocuments:[...request.eligibleDocuments,...request.eligibleDocuments]},{enabled:true,contextId:"CTX",contextVersion:1});assert.equal(result.status,"VALIDATION_FAILED");assert.deepEqual(calls,{embed:0,vector:0,lexical:0});});
