import assert from "node:assert/strict";
import test from "node:test";

import { ProviderResolutionExecutionService } from "../../../src/services/providers/provider-resolution-execution.service.js";
import {
  PROVIDER_RESOLUTION_ATTEMPT_OUTCOMES,
  PROVIDER_RESOLUTION_EXECUTION_FAILURE_CODES,
} from "../../../src/types/provider-resolution-execution.types.js";

const service = new ProviderResolutionExecutionService();
const definition = (providerKey: string, providerType = "DIRECT") => ({
  providerKey, displayName: providerKey, providerType, authorityLevel: providerType === "MANUAL" ? "MANUAL_REVIEWED" : providerType === "PROXY" ? "APPROVED_PROXY" : "EXCHANGE", costTier: providerType === "MANUAL" ? "MANUAL" : "FREE", supportedFactorKeys: ["MARKET.PRICE"], enabled: true,
});
const binding = (keys = ["PRIMARY", "FALLBACK"]) => ({ factorKey: "MARKET.PRICE", orderedProviderKeys: keys });
const catalog = (providers = [definition("PRIMARY"), definition("FALLBACK")], bound = binding()) => ({ providers, bindings: [bound] });
const health = (providerKey: string, state = "HEALTHY") => ({ assessed: true, providerKey, policyId: "HEALTH_V1", policyVersion: 1, state, reasonCodes: state === "HEALTHY" ? ["WITHIN_HEALTHY_THRESHOLDS"] : state === "DEGRADED" ? ["RECENT_FAILURES_PRESENT"] : state === "UNKNOWN" ? ["NO_TELEMETRY"] : ["NO_RECENT_SUCCESS"], metrics: { errorRate: state === "HEALTHY" ? 0 : null, telemetryAgeMs: 1, successAgeMs: 1 } });
const policy = (overrides: Record<string, unknown> = {}) => ({ policyId: "RESOLUTION_V1", policyVersion: 1, factorKey: "MARKET.PRICE", preferredProviderRule: { allowedStates: ["HEALTHY"] }, fallbackProviderRule: { allowedStates: ["HEALTHY", "DEGRADED"] }, allowDegradedPreferredProvider: false, noUsableProviderOutcome: "MANUAL_REQUIRED", confidenceAdjustments: { resolved: 0, degradedPrimaryUsed: -0.1, fallbackUsed: -0.15, proxyUsed: -0.25, manualRequired: -0.4, unresolved: -1 }, ...overrides });
const request = (overrides: Record<string, unknown> = {}) => { const bound = binding(); return { catalog: catalog(undefined, bound), binding: bound, healthAssessments: [health("PRIMARY"), health("FALLBACK")], policy: policy(), ...overrides }; };
const execute = (overrides: Record<string, unknown> = {}) => service.execute(request(overrides) as never);
const ok = (result: ReturnType<typeof execute>) => { assert.equal(result.executed, true); if (!result.executed) throw new Error("execution failed"); return result.result; };
const fail = (overrides: Record<string, unknown>, code: string) => { const result = execute(overrides); assert.equal(result.executed, false); if (!result.executed) assert.equal(result.code, code); };

test("exports frozen attempt outcomes and failure codes", () => { assert.deepEqual(PROVIDER_RESOLUTION_ATTEMPT_OUTCOMES, ["SELECTED", "REJECTED_HEALTH", "NOT_ATTEMPTED"]); assert.equal(PROVIDER_RESOLUTION_EXECUTION_FAILURE_CODES.length, 14); assert(PROVIDER_RESOLUTION_EXECUTION_FAILURE_CODES.includes("PROVIDER_NOT_LIVE_EXECUTION_ELIGIBLE")); assert(Object.isFrozen(PROVIDER_RESOLUTION_ATTEMPT_OUTCOMES)); });
test("selects a healthy preferred direct provider normally", () => { const result = ok(execute()); assert.equal(result.resolved, true); assert.equal(result.resolutionStatus, "RESOLVED"); assert.equal(result.selectedProviderOrder, 0); assert.equal(result.confidenceAdjustment, 0); assert.deepEqual(result.warningCodes, []); assert.deepEqual(result.attempts.map((a) => a.outcome), ["SELECTED", "NOT_ATTEMPTED"]); });
test("selects an explicitly allowed degraded preferred provider visibly", () => { const result = ok(execute({ healthAssessments: [health("PRIMARY", "DEGRADED"), health("FALLBACK")], policy: policy({ preferredProviderRule: { allowedStates: ["HEALTHY", "DEGRADED"] }, allowDegradedPreferredProvider: true }) })); assert.equal(result.resolutionStatus, "DEGRADED_PRIMARY_USED"); assert.equal(result.confidenceAdjustment, -0.1); assert.deepEqual(result.warningCodes, ["PREFERRED_PROVIDER_DEGRADED", "DEGRADED_PROVIDER_SELECTED"]); });
test("rejects degraded preferred and selects direct fallback", () => { const result = ok(execute({ healthAssessments: [health("PRIMARY", "DEGRADED"), health("FALLBACK")] })); assert.equal(result.resolutionStatus, "FALLBACK_USED"); assert.equal(result.selectedProviderKey, "FALLBACK"); assert.deepEqual(result.warningCodes, ["PREFERRED_PROVIDER_DEGRADED", "FALLBACK_PROVIDER_SELECTED"]); });
test("keeps manual fallback visible", () => { const bound = binding(["PRIMARY", "MANUAL"]); const result = ok(execute({ catalog: catalog([definition("PRIMARY"), definition("MANUAL", "MANUAL")], bound), binding: bound, healthAssessments: [health("PRIMARY", "DEGRADED"), health("MANUAL")] })); assert.equal(result.resolutionStatus, "FALLBACK_USED"); assert.equal(result.selectedProviderType, "MANUAL"); assert.deepEqual(result.warningCodes, ["PREFERRED_PROVIDER_DEGRADED", "FALLBACK_PROVIDER_SELECTED", "MANUAL_PROVIDER_SELECTED"]); });
test("maps preferred and fallback proxy selection to PROXY_USED", () => { const preferredBound = binding(["PROXY", "OTHER"]); let result = ok(execute({ catalog: catalog([definition("PROXY", "PROXY"), definition("OTHER")], preferredBound), binding: preferredBound, healthAssessments: [health("PROXY"), health("OTHER")] })); assert.equal(result.resolutionStatus, "PROXY_USED"); assert.deepEqual(result.warningCodes, ["PROXY_PROVIDER_SELECTED"]); const fallbackBound = binding(["PRIMARY", "PROXY"]); result = ok(execute({ catalog: catalog([definition("PRIMARY"), definition("PROXY", "PROXY")], fallbackBound), binding: fallbackBound, healthAssessments: [health("PRIMARY", "UNAVAILABLE"), health("PROXY")] })); assert.equal(result.resolutionStatus, "PROXY_USED"); assert.deepEqual(result.warningCodes, ["PREFERRED_PROVIDER_UNAVAILABLE", "FALLBACK_PROVIDER_SELECTED", "PROXY_PROVIDER_SELECTED"]); });
test("allows degraded fallback and stops traversal", () => { const bound = binding(["PRIMARY", "F1", "F2"]); const result = ok(execute({ catalog: catalog([definition("PRIMARY"), definition("F1"), definition("F2")], bound), binding: bound, healthAssessments: [health("PRIMARY", "UNKNOWN"), health("F1", "DEGRADED"), health("F2")] })); assert.equal(result.selectedProviderKey, "F1"); assert.deepEqual(result.warningCodes, ["PREFERRED_PROVIDER_UNKNOWN", "FALLBACK_PROVIDER_SELECTED", "DEGRADED_PROVIDER_SELECTED"]); assert.deepEqual(result.attempts.map((a) => a.outcome), ["REJECTED_HEALTH", "SELECTED", "NOT_ATTEMPTED"]); });
test("returns manual-required and unresolved no-provider results", () => { let result = ok(execute({ healthAssessments: [health("PRIMARY", "UNAVAILABLE"), health("FALLBACK", "UNKNOWN")] })); assert.equal(result.resolved, false); assert.equal(result.resolutionStatus, "MANUAL_REQUIRED"); assert.equal(result.confidenceAdjustment, -0.4); assert.deepEqual(result.warningCodes, ["PREFERRED_PROVIDER_UNAVAILABLE", "NO_USABLE_PROVIDER", "MANUAL_INTERVENTION_REQUIRED"]); result = ok(execute({ healthAssessments: [health("PRIMARY", "UNAVAILABLE"), health("FALLBACK", "UNKNOWN")], policy: policy({ noUsableProviderOutcome: "UNRESOLVED" }) })); assert.equal(result.resolutionStatus, "UNRESOLVED"); assert.equal(result.confidenceAdjustment, -1); assert.deepEqual(result.warningCodes, ["PREFERRED_PROVIDER_UNAVAILABLE", "NO_USABLE_PROVIDER"]); assert(result.attempts.every((a) => a.outcome === "REJECTED_HEALTH")); });
test("rejects malformed boundaries in prescribed order", () => { for (const value of [null, [], {}]) { const r = service.execute(value as never); assert.equal(!r.executed && r.code, "INVALID_REQUEST"); } fail({ catalog: null, binding: null, policy: null }, "INVALID_CATALOG_BOUNDARY"); fail({ binding: null, policy: null }, "INVALID_BINDING_BOUNDARY"); fail({ policy: null, healthAssessments: null }, "INVALID_POLICY_BOUNDARY"); fail({ healthAssessments: null }, "INVALID_HEALTH_ASSESSMENTS_BOUNDARY"); });
test("rejects factor and binding lineage mismatches", () => { let reads = 0; const shiftingBinding = { get factorKey() { reads += 1; return reads === 1 ? "MARKET.PRICE" : "OTHER"; }, orderedProviderKeys: ["PRIMARY", "FALLBACK"] }; fail({ binding: shiftingBinding }, "FACTOR_MISMATCH"); fail({ binding: binding(["FALLBACK", "PRIMARY"]) }, "BINDING_NOT_IN_CATALOG"); });
test("rejects a bound provider missing from catalog", () => { const bound = binding(["PRIMARY", "MISSING"]); fail({ catalog: catalog([definition("PRIMARY")], bound), binding: bound, healthAssessments: [health("PRIMARY"), health("MISSING")] }, "BOUND_PROVIDER_MISSING_FROM_CATALOG"); });
test("validates duplicate, missing, and unexpected health coverage in order", () => { fail({ healthAssessments: [health("PRIMARY"), health("PRIMARY")] }, "DUPLICATE_HEALTH_ASSESSMENT"); fail({ healthAssessments: [health("PRIMARY")] }, "HEALTH_ASSESSMENT_MISSING"); fail({ healthAssessments: [health("PRIMARY"), health("FALLBACK"), health("EXTRA")] }, "UNEXPECTED_HEALTH_ASSESSMENT"); fail({ healthAssessments: [health("PRIMARY"), health("PRIMARY"), health("EXTRA")] }, "DUPLICATE_HEALTH_ASSESSMENT"); });
test("fails closed when healthy preferred is rejected by inconsistent validated rules", () => { fail({ policy: policy({ preferredProviderRule: { allowedStates: ["DEGRADED"] }, allowDegradedPreferredProvider: true }) }, "INVALID_RESOLUTION_STATE"); });
test("preserves exact attempt and warning order without duplicates", () => { const result = ok(execute({ healthAssessments: [health("PRIMARY", "DEGRADED"), health("FALLBACK", "DEGRADED")] })); assert.deepEqual(result.attempts.map((a) => [a.order, a.providerKey]), [[0, "PRIMARY"], [1, "FALLBACK"]]); assert.equal(new Set(result.warningCodes).size, result.warningCodes.length); });
test("returns detached deeply frozen minimized deterministic results", () => { const source = request(); const execution = service.execute(source as never); const result = ok(execution); (source.binding.orderedProviderKeys as string[]).reverse(); source.healthAssessments.reverse(); source.policy.confidenceAdjustments.fallbackUsed = -99; assert.equal(result.requestedProviderKey, "PRIMARY"); assert.deepEqual(result.attempts.map((a) => a.providerKey), ["PRIMARY", "FALLBACK"]); assert(Object.isFrozen(execution)); assert(Object.isFrozen(result)); assert(Object.isFrozen(result.attempts)); assert(Object.isFrozen(result.attempts[0])); assert(Object.isFrozen(result.warningCodes)); assert.throws(() => (result.attempts as unknown[]).push({}), TypeError); const serialized = JSON.stringify(result); for (const field of ["Evidence", "score", "executionId", "resolvedAt", "createdAt", "durationMs", "telemetry", "reasonCodes"]) assert(!serialized.includes(`"${field}":`)); assert.deepEqual(execute(), execute()); });
