import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { ProviderResolutionRunnerRegistry } from "../../../src/registries/provider-resolution-runner.registry.js";
import { ProviderResolutionCompositionService } from "../../../src/services/provider-resolution-composition.service.js";
import { PROVIDER_RESOLUTION_COMPOSITION_FAILURE_CODES, PROVIDER_RESOLUTION_COMPOSITION_STAGES } from "../../../src/types/provider-resolution-composition.types.js";

const service = new ProviderResolutionCompositionService();
const adapter = (adapterId: string) => ({ adapterId, readCandidates: async () => { throw new Error("composition must delegate only to runner"); } });
const selected = (overrides: Record<string, unknown> = {}) => ({ executed: true as const, result: { resolved: true as const, factorKey: "MARKET.PRICE", policyId: "POLICY_V1", policyVersion: 1, requestedProviderKey: "PRIMARY", selectedProviderKey: "FALLBACK", selectedProviderType: "MANUAL", selectedProviderOrder: 1, resolutionStatus: "FALLBACK_USED", confidenceAdjustment: -0.15, warningCodes: ["PREFERRED_PROVIDER_DEGRADED", "FALLBACK_PROVIDER_SELECTED", "MANUAL_PROVIDER_SELECTED"], attempts: [], ...overrides } });
const noProvider = () => ({ executed: true as const, result: { resolved: false as const, factorKey: "MARKET.PRICE", policyId: "POLICY_V1", policyVersion: 1, requestedProviderKey: "PRIMARY", selectedProviderKey: null, selectedProviderType: null, selectedProviderOrder: null, resolutionStatus: "MANUAL_REQUIRED", confidenceAdjustment: -0.4, warningCodes: ["NO_USABLE_PROVIDER", "MANUAL_INTERVENTION_REQUIRED"], attempts: [] } });
const completed = (runnerId: string, overrides: Record<string, unknown> = {}) => ({ providerKey: runnerId, status: "COMPLETED", candidateCount: 1, createdCount: 1, duplicateCount: 0, rejectedCount: 0, failedCount: 0, results: [{ index: 0, result: { status: "CREATED", evidenceId: "ev_1", deduplicationKey: "secret-key" } }], ...overrides });
const setup = (definitions: Array<{ providerKey: string; runnerId: string; result?: unknown; throws?: boolean }> = [{ providerKey: "FALLBACK", runnerId: "FALLBACK_V1" }]) => { const calls = new Map<string, number>(); const registrations = definitions.map((definition) => ({ providerKey: definition.providerKey, runnerId: definition.runnerId, runner: { run: async () => { calls.set(definition.providerKey, (calls.get(definition.providerKey) ?? 0) + 1); if (definition.throws) throw new Error("Authorization: Bearer SECRET raw body"); return definition.result ?? completed(definition.runnerId); } } })); return { calls, registry: new ProviderResolutionRunnerRegistry(registrations as never) }; };
const compose = (resolution: any, registry: any, adapterId = "FALLBACK_V1") => service.compose({ resolution, runnerRegistry: registry, executionInput: { adapter: adapter(adapterId) } } as never);

test("exports frozen stage and failure vocabularies", () => { assert.deepEqual(PROVIDER_RESOLUTION_COMPOSITION_STAGES, ["RESOLUTION_INPUT", "RUNNER_LOOKUP", "PROVIDER_EXECUTION", "EVIDENCE_INGESTION"]); assert.equal(PROVIDER_RESOLUTION_COMPOSITION_FAILURE_CODES.length, 14); assert(Object.isFrozen(PROVIDER_RESOLUTION_COMPOSITION_STAGES)); });
test("executes only the Phase 3D-selected fallback exactly once", async () => { const env = setup([{ providerKey: "PRIMARY", runnerId: "PRIMARY_V1" }, { providerKey: "FALLBACK", runnerId: "FALLBACK_V1" }, { providerKey: "PROXY", runnerId: "PROXY_V1" }]); const result = await compose(selected(), env.registry); assert.equal(result.composed, true); assert.deepEqual([...env.calls], [["FALLBACK", 1]]); if (result.composed && result.resolved) { assert.equal(result.resolutionStatus, "FALLBACK_USED"); assert.equal(result.confidenceAdjustment, -0.15); assert.deepEqual(result.warningCodes, selected().result.warningCodes); assert.equal(result.evidenceOutcome.evidenceIds[0], "ev_1"); assert(!JSON.stringify(result).includes("secret-key")); assert(result.stages.every((stage) => stage.state === "COMPLETED")); } });
test("healthy primary, proxy, and degraded-primary statuses remain exact", async () => { for (const [key, type, status, id] of [["PRIMARY", "DIRECT", "RESOLVED", "PRIMARY_V1"], ["PROXY", "PROXY", "PROXY_USED", "PROXY_V1"], ["PRIMARY", "DIRECT", "DEGRADED_PRIMARY_USED", "PRIMARY_V1"]] as const) { const env = setup([{ providerKey: key, runnerId: id }]); const result = await compose(selected({ selectedProviderKey: key, selectedProviderType: type, resolutionStatus: status }), env.registry, id); assert(result.composed && result.resolved); assert.equal(result.resolutionStatus, status); assert.equal(env.calls.get(key), 1); } });
test("no-provider result skips lookup and every runner", async () => { let lookups = 0; const result = await compose(noProvider(), { get: () => { lookups += 1; throw new Error("no lookup"); } }); assert(result.composed && !result.resolved); assert.equal(lookups, 0); assert.equal(result.providerExecutionStatus, "SKIPPED"); assert.deepEqual(result.stages.map((x) => x.state), ["COMPLETED", "SKIPPED", "SKIPPED", "SKIPPED"]); });
test("fails closed for Phase 3D failure and malformed boundaries", async () => { const env = setup(); for (const resolution of [{ executed: false, code: "INVALID_REQUEST", factorKey: null, policyId: null }, null, {}]) { const result = await compose(resolution, env.registry); assert(!result.composed); assert.equal(result.code, "INVALID_RESOLUTION_BOUNDARY"); } assert.equal(env.calls.size, 0); });
test("missing selected runner and identity mismatch execute nothing", async () => { let env = setup([{ providerKey: "PRIMARY", runnerId: "PRIMARY_V1" }]); let result = await compose(selected(), env.registry); assert(!result.composed && result.code === "RUNNER_NOT_REGISTERED"); assert.deepEqual(result.stages.map((x) => x.state), ["COMPLETED", "FAILED", "SKIPPED", "SKIPPED"]); assert.equal(env.calls.size, 0); env = setup(); result = await compose(selected(), env.registry, "WRONG_V1"); assert(!result.composed && result.code === "RUNNER_IDENTITY_MISMATCH"); assert.equal(env.calls.size, 0); });
test("runner typed failure, throw, and malformed result are explicit and never retried", async () => { for (const [definition, code] of [[{ providerKey: "FALLBACK", runnerId: "FALLBACK_V1", result: { providerKey: "FALLBACK_V1", status: "FAILED", failureCode: "ADAPTER_EXECUTION_FAILED", candidateCount: 0, createdCount: 0, duplicateCount: 0, rejectedCount: 0, failedCount: 0, results: [] } }, "RUNNER_EXECUTION_FAILED"], [{ providerKey: "FALLBACK", runnerId: "FALLBACK_V1", throws: true }, "RUNNER_EXECUTION_THROWN"], [{ providerKey: "FALLBACK", runnerId: "FALLBACK_V1", result: { status: "COMPLETED" } }, "RUNNER_RESULT_INVALID"]] as const) { const env = setup([definition]); const result = await compose(selected(), env.registry); assert(!result.composed && result.code === code); assert.equal(env.calls.get("FALLBACK"), 1); assert(!JSON.stringify(result).includes("SECRET")); assert.deepEqual(result.stages.map((x) => x.state), ["COMPLETED", "COMPLETED", "FAILED", "SKIPPED"]); } });
test("preserves rejected-only partial and valid zero-candidate Phase 1 semantics", async () => { let env = setup([{ providerKey: "FALLBACK", runnerId: "FALLBACK_V1", result: completed("FALLBACK_V1", { status: "PARTIAL", createdCount: 0, rejectedCount: 1, results: [{ index: 0, result: { status: "REJECTED", code: "INVALID_CANDIDATE" } }] }) }]); let result = await compose(selected(), env.registry); assert(result.composed && result.resolved && result.providerExecutionStatus === "PARTIAL"); env = setup([{ providerKey: "FALLBACK", runnerId: "FALLBACK_V1", result: completed("FALLBACK_V1", { candidateCount: 0, createdCount: 0, results: [] }) }]); result = await compose(selected(), env.registry); assert(result.composed && result.resolved && result.candidateCount === 0 && result.evidenceOutcome.evidenceIds.length === 0); });
test("maps runner-contained ingestion failure without retry or second ingestion", async () => { const env = setup([{ providerKey: "FALLBACK", runnerId: "FALLBACK_V1", result: completed("FALLBACK_V1", { status: "PARTIAL", createdCount: 0, failedCount: 1, results: [{ index: 0, result: { status: "FAILED", code: "PERSISTENCE_FAILED" } }] }) }, { providerKey: "PROXY", runnerId: "PROXY_V1" }]); const result = await compose(selected(), env.registry); assert(!result.composed && result.code === "EVIDENCE_INGESTION_FAILED"); assert.deepEqual([...env.calls], [["FALLBACK", 1]]); assert.deepEqual(result.stages.map((x) => x.state), ["COMPLETED", "COMPLETED", "COMPLETED", "FAILED"]); });
test("detaches and deeply freezes composition projections without generated metadata", async () => { const resolution = selected(); const env = setup(); const result = await compose(resolution, env.registry); assert(result.composed && result.resolved); (resolution.result.warningCodes as string[]).length = 0; assert.equal(result.warningCodes.length, 3); assert(Object.isFrozen(result)); assert(Object.isFrozen(result.warningCodes)); assert(Object.isFrozen(result.stages)); assert(Object.isFrozen(result.stages[0])); assert(Object.isFrozen(result.evidenceOutcome)); assert(Object.isFrozen(result.evidenceOutcome.results)); assert.throws(() => (result.warningCodes as string[]).push("x"), TypeError); const serialized = JSON.stringify(result); for (const field of ["compositionId", "composedAt", "durationMs", "raw", "deduplicationKey"]) assert(!serialized.includes(field)); });
test("source audit contains no Phase 2, scoring, selection, health, clock, retry, or randomness imports", () => { const source = readFileSync(new URL("../../../src/services/provider-resolution-composition.service.ts", import.meta.url), "utf8"); for (const token of ["factor-input", "factor-evaluator", "scoring", "provider-health", "provider-catalog.service", "provider-resolution-execution.service", "Date.now", "Math.random", "randomUUID", "retry"]) assert(!source.includes(token)); });
