import assert from "node:assert/strict";
import test from "node:test";
import { ScoringEngineService, type ScoringEngineInput } from "../../../src/services/scoring-engine.service.js";
import { GenericRelationshipFactorEvaluator } from "../../../src/services/generic-relationship-factor-evaluator.js";
import { GenericFactorCompatibilityDispatcher, GenericFactorLegacyResultAdapter } from "../../../src/services/generic-factor-legacy-compatibility.service.js";
import { factorRegistry } from "../../../src/registries/factor.registry.js";
import { sharedFeatureFlagService } from "../../../src/config/feature-flags.js";
import type { AssembledFactorInput } from "../../../src/types/factor-input-assembly.types.js";

const KEY = "GENERIC_FACTOR:CRYPTO.ETF_NET_FLOW";
const AT = new Date("2026-08-05T10:00:00.000Z");
const factorInput = (value = 420): AssembledFactorInput => ({ factorKey: "CRYPTO.ETF_NET_FLOW", factorDefinitionVersion: 1, subject: { type: "ASSET", key: "BTC" }, evidenceId: "ETF_EVIDENCE_1", value: { type: "NUMBER", value, unit: "USD" }, source: { sourceType: "MARKET_DATA", provider: "TEST_ETF_PROVIDER", sourceId: "TEST_ETF_DAILY_V1", priority: 100 }, observedAt: new Date("2026-08-05T09:00:00.000Z"), evaluatedAt: AT, confidence: 1, freshness: { status: "FRESH", ageMs: 3_600_000, maxAgeMs: 86_400_000 } });
const template = (key = KEY, policy: "BLOCK" | "PARTIAL" | "IGNORE" = "BLOCK") => ({ templateKey: "GENERIC_TEST", baseTemplateKey: "CRYPTO_SPOT_INTRADAY_V1" as const, templateName: "Generic test", scope: "SYSTEM" as const, version: 1, marketType: "CRYPTO" as const, tradeStyle: "INTRADAY", instrumentType: "SPOT" as const, maxScore: 100, aggregationMode: "NORMALIZE_EXECUTED" as const, permissionThresholds: { rejectBelow: 40, waitBelow: 60, takeSmallRiskBelow: 75, takeTradeAtOrAbove: 75 }, sections: [{ sectionKey: "ETF", label: "ETF", weight: 100, enabled: true, missingDataPolicy: policy, evaluators: [{ evaluatorKey: key, label: "ETF", weight: 100, enabled: true, missingDataPolicy: policy, config: {} }] }] });
const input = (change: Partial<ScoringEngineInput> = {}): ScoringEngineInput => ({ scoringTemplateKey: "CRYPTO_SPOT_INTRADAY_V1", scoringTemplateVersion: "1", resolvedTemplate: template(), marketType: "CRYPTO", tradeStyle: "INTRADAY", instrumentType: "SPOT", rewardRiskRatio: 2, evaluatedAt: AT, genericFactorInputs: { "CRYPTO.ETF_NET_FLOW": { relationshipType: "DIRECT", input: factorInput() } }, ...change });
const withoutGeneric = (change: Partial<ScoringEngineInput> = {}): ScoringEngineInput => { const value = input(change); delete value.genericFactorInputs; return value; };
const harness = (enabled: boolean) => { const calls = { compatibility: 0, execution: 0 }; const compatibility = new GenericFactorCompatibilityDispatcher({ enabled: true, factorRegistry, adapter: new GenericFactorLegacyResultAdapter() }); const service = new ScoringEngineService(undefined, undefined, { featureFlags: { isEnabled: () => enabled }, genericCompatibility: { dispatch: (request) => { calls.compatibility++; return compatibility.dispatch(request); } }, genericExecution: { execute: ({ relationshipType, input }) => { calls.execution++; return new GenericRelationshipFactorEvaluator({ relationshipType, expectedUnit: "USD", thresholds: { strongNegativeMax: -300, negativeMax: -100, positiveMin: 100, strongPositiveMin: 300 }, contributions: { strongNegative: -2, negative: -1, neutral: 0, positive: 1, strongPositive: 2 }, minimumPoints: -2, maximumPoints: 2 }).evaluate(input); } } }); return { service, calls }; };

test("flag OFF preserves the existing unknown-evaluator behavior without generic calls", () => { const h = harness(false); const result = h.service.score(input()); assert.equal(result.breakdown.evaluatorResults[0]?.status, "BLOCKED"); assert.deepEqual(result.breakdown.evaluatorResults[0]?.reasonCodes, ["UNKNOWN_SCORING_EVALUATOR"]); assert.deepEqual(h.calls, { compatibility: 0, execution: 0 }); });
test("the repository generic evaluator feature default remains OFF", () => { assert.equal(sharedFeatureFlagService.isEnabled("GENERIC_EVALUATOR_ENABLED"), false); const result = new ScoringEngineService().score(input()); assert.deepEqual(result.breakdown.evaluatorResults[0]?.reasonCodes, ["UNKNOWN_SCORING_EVALUATOR"]); });
test("flag ON executes DIRECT and INVERSE exactly once through compatibility", () => { for (const [relationshipType, score] of [["DIRECT", 100], ["INVERSE", 0]] as const) { const h = harness(true); const result = h.service.score(input({ genericFactorInputs: { "CRYPTO.ETF_NET_FLOW": { relationshipType, input: factorInput() } } })); assert.equal(result.breakdown.evaluatorResults[0]?.score, score); assert.deepEqual(h.calls, { compatibility: 1, execution: 1 }); } });
test("non-generic rules never call generic dependencies", () => { const h = harness(true); const result = h.service.score(withoutGeneric({ resolvedTemplate: template("REWARD_RISK_RATIO") })); assert.equal(result.breakdown.evaluatorResults[0]?.status, "EXECUTED"); assert.deepEqual(h.calls, { compatibility: 0, execution: 0 }); });
test("missing input remains typed and follows template missing-data policy", () => { for (const [policy, expected] of [["BLOCK", "UNAVAILABLE"], ["PARTIAL", "PARTIAL_DATA"], ["IGNORE", "PARTIAL_DATA"]] as const) { const h = harness(true); const result = h.service.score(withoutGeneric({ resolvedTemplate: template(KEY, policy) })); const evaluator = result.breakdown.evaluatorResults[0]!; assert.equal(evaluator.status, "BLOCKED"); assert.deepEqual(evaluator.reasonCodes, ["MISSING_EVIDENCE"]); assert.equal(result.scoreStatus, expected); assert.equal(h.calls.execution, 0); assert.equal(h.calls.compatibility, 1); } });
test("malformed and unknown generic keys preserve explicit unsupported behavior", () => { for (const key of ["GENERIC_FACTOR:", "GENERIC_FACTOR:UNKNOWN"]) { const h = harness(true); const result = h.service.score(input({ resolvedTemplate: template(key) })); assert.equal(result.breakdown.evaluatorResults[0]?.status, "BLOCKED"); assert.equal(h.calls.execution, 0); } });
test("unsupported generic relationships fail explicitly without fallback", () => { const h = harness(true); const result = h.service.score(input({ genericFactorInputs: { "CRYPTO.ETF_NET_FLOW": { relationshipType: "VETO", input: factorInput() } } })); assert.equal(result.breakdown.evaluatorResults[0]?.status, "BLOCKED"); assert.deepEqual(result.breakdown.evaluatorResults[0]?.reasonCodes, ["UNSUPPORTED_RELATIONSHIP"]); assert.deepEqual(h.calls, { compatibility: 1, execution: 1 }); });
test("invalid explicit input is never inferred from price volume or CVD", () => { const h = harness(true); const invalid = { ...factorInput(), value: { type: "NUMBER", value: Number.NaN, unit: "USD" } } as AssembledFactorInput; const result = h.service.score(input({ marketSnapshot: { price: 65000 } as never, runtime: { currentCvdAvailable: true, cvd: { available: true, currentCVD: 99, bufferCount: 1 } }, genericFactorInputs: { "CRYPTO.ETF_NET_FLOW": { relationshipType: "DIRECT", input: invalid } } })); assert.equal(result.breakdown.evaluatorResults[0]?.status, "BLOCKED"); assert.notEqual(result.breakdown.evaluatorResults[0]?.score, 50); });
test("global reward-risk forced rejection remains after generic dispatch", () => { const h = harness(true); const result = h.service.score(input({ rewardRiskRatio: 0.8 })); assert.equal(result.breakdown.evaluatorResults[0]?.score, 100); assert.equal(result.score, 30); assert.equal(result.permission, "REJECT"); assert.deepEqual(h.calls, { compatibility: 1, execution: 1 }); });
test("repeated execution is equal detached and does not mutate explicit inputs", () => { const request = input(); const original = structuredClone(request); const first = harness(true).service.score(request); const second = harness(true).service.score(request); assert.deepEqual(first, second); assert.deepEqual(request, original); assert.notEqual(request.genericFactorInputs?.["CRYPTO.ETF_NET_FLOW"]?.input.observedAt, first.breakdown.evaluatorResults[0]?.metadata?.observedAt); });
