import type { EditableScoringSectionDefinition, ScoringTemplateKey } from "./scoring.types.js";
import type { InstrumentType, MarketType } from "./market-data.types.js";
import type { AcceptTemplateDraftCandidateRequest, TemplateDraftAcceptedBinding } from "./template-draft-acceptance.types.js";
import type { TemplateDraftGenerationResult } from "./template-draft-generation.types.js";
export type TemplateDraftCreateCommand = Readonly<{ userId: string; templateKey: string; baseTemplateKey: ScoringTemplateKey; templateName: string; description?: string; marketType: MarketType; tradeStyle: string; instrumentType: InstrumentType; sections: readonly EditableScoringSectionDefinition[] }>;
export type TemplateDraftProjectionLineage = Readonly<{ requestId: string; candidateId: string; candidateSchemaVersion: number; generationAttemptId: string; promptId: string; promptVersion: number; registryProjectionId: string; registryProjectionVersion: number; registryProjectionDigest: string; validationPolicyId: string; validationPolicyVersion: number; acceptanceId: string; acceptanceVersion: number; authenticatedOwnerId: string; acceptedBindingIds: readonly string[]; excludedConceptIds: readonly string[]; createdTemplateId: string | null; createdTemplateVersion: number | null }>;
export type TemplateDraftProjectionIssue = Readonly<{ code: string; explanation: string }>;
export type TemplateDraftProjectionResult = Readonly<{ status: "CREATED"; template: Readonly<{ id: string; templateKey: string; version: number; scope: "USER"; status: "DRAFT"; ownerId: string }>; acceptedBindingIds: readonly string[]; excludedConceptIds: readonly string[]; lineage: TemplateDraftProjectionLineage }> | Readonly<{ status: "ACCEPTANCE_VALIDATION_FAILED" | "STALE_CANDIDATE" | "OWNERSHIP_FAILED" | "PERSISTENCE_FAILED"; issues: readonly TemplateDraftProjectionIssue[]; lineage: TemplateDraftProjectionLineage }>;
export type TemplateDraftProjectionRequest = Readonly<{ acceptance: AcceptTemplateDraftCandidateRequest; generation: Extract<TemplateDraftGenerationResult, { status: "COMPLETED" | "PARTIAL" }>; acceptedBindings: readonly TemplateDraftAcceptedBinding[] }>;
