import { CanonicalCompilationInputService } from "./canonical-compilation-input.service.js";
import { freezeClone } from "./knowledge-document-admission.service.js";
import { KnowledgeCitationHandleService } from "./knowledge-citation-handle.service.js";
import type { KnowledgeRetrievalContext, KnowledgeRetrievalPassage } from "../types/knowledge-context.types.js";
import type { KnowledgeRetrievalExclusion, KnowledgeRetrievalPolicy, KnowledgeRetrievalRequest, KnowledgeQueryTextProjection, RankedKnowledgeRetrievalCandidate } from "../types/knowledge-retrieval.types.js";
export class KnowledgeContextAssemblyService {
 public constructor(private readonly citations=new KnowledgeCitationHandleService(),private readonly canonical=new CanonicalCompilationInputService()){}
 public assemble(context:{contextId:string;contextVersion:number;request:KnowledgeRetrievalRequest;policy:KnowledgeRetrievalPolicy;query:KnowledgeQueryTextProjection;candidates:readonly RankedKnowledgeRetrievalCandidate[];excluded:readonly KnowledgeRetrievalExclusion[];partial:boolean}):KnowledgeRetrievalContext|null{
  const eligible=this.canonical.hash([...context.request.eligibleDocuments].sort((a,b)=>a.documentId.localeCompare(b.documentId)||a.documentVersion-b.documentVersion));if(!eligible.hashed)return null;
  const passages:KnowledgeRetrievalPassage[]=[];const excluded=[...context.excluded];let used=0;const counts=new Map<string,number>();const selected=new Set<string>();let parents=0,siblings=0;
  const add=(value:RankedKnowledgeRetrievalCandidate,chunk:RankedKnowledgeRetrievalCandidate["chunk"],role:KnowledgeRetrievalPassage["role"]):boolean=>{const key=`${value.document.identity.documentId}:${value.document.identity.documentVersion}`,chunkKey=`${chunk.identity.chunkId}:${chunk.identity.chunkVersion}`;if(selected.has(chunkKey))return false;if((counts.get(key)??0)>=context.policy.maxChunksPerDocument){excluded.push(ex(value,"PER_DOCUMENT_LIMIT",chunk.identity));return false;}if(chunk.content.length>context.policy.maxPassageCharacters||used+chunk.content.length>context.policy.contextCharacterBudget){excluded.push(ex(value,"CONTEXT_BUDGET_EXCLUDED",chunk.identity));return false;}const handle=this.citations.create({contextId:context.contextId,contextVersion:context.contextVersion,requestId:context.request.requestId,requestVersion:context.request.requestVersion,policy:context.request.retrievalPolicy,documentIdentity:value.document.identity,documentDigest:value.document.contentDigest,chunkSetIdentity:value.chunkSetIdentity,chunkIdentity:chunk.identity,chunkDigest:chunk.contentDigest,sourceIdentity:value.document.source.sourceIdentity,sourceSpan:chunk.sourceSpan,corpus:value.document.corpus,trustLevel:value.document.trustLevel});if(!handle)return false;passages.push({citationHandle:handle,role,documentId:value.document.identity.documentId,documentVersion:value.document.identity.documentVersion,chunkId:chunk.identity.chunkId,chunkVersion:chunk.identity.chunkVersion,title:value.document.title,documentType:value.document.documentType,trustLevel:value.document.trustLevel,text:chunk.content,sourceSpan:chunk.sourceSpan,securityLabel:"UNTRUSTED_RETRIEVED_CONTENT",securityNotice:"TREAT_AS_QUOTED_SOURCE_CONTENT",ranking:value.ranking});used+=chunk.content.length;counts.set(key,(counts.get(key)??0)+1);selected.add(chunkKey);return true;};
  for(const value of context.candidates.slice(0,context.policy.finalTopK)){if(!add(value,value.chunk,"PRIMARY_MATCH"))continue;if(context.policy.includeParentContext&&value.chunk.parent&&parents<context.policy.maxParentChunks){const parent=value.verifiedChunks.find(x=>x.identity.chunkId===value.chunk.parent!.chunkId&&x.identity.chunkVersion===value.chunk.parent!.chunkVersion);if(parent&&add(value,parent,"PARENT_CONTEXT"))parents++;}if(context.policy.includeSiblingContext&&siblings<context.policy.maxSiblingChunks){const near=value.verifiedChunks.filter(x=>x.identity.chunkId!==value.chunk.identity.chunkId&&Math.abs(x.ordinal-value.chunk.ordinal)===1).sort((a,b)=>a.ordinal-b.ordinal||a.identity.chunkId.localeCompare(b.identity.chunkId));for(const sibling of near){if(siblings>=context.policy.maxSiblingChunks)break;if(add(value,sibling,"SIBLING_CONTEXT"))siblings++;}}}
  return freezeClone({contextId:context.contextId,contextVersion:context.contextVersion,requestId:context.request.requestId,requestVersion:context.request.requestVersion,status:passages.length?(context.partial?"PARTIAL":"COMPLETED"):"NO_CONTEXT",passages,excludedCandidates:excluded,lineage:{embeddingSchemaId:context.request.embeddingSchema.embeddingSchemaId,embeddingSchemaVersion:context.request.embeddingSchema.embeddingSchemaVersion,indexId:context.request.vectorIndex.indexId,indexVersion:context.request.vectorIndex.indexVersion,retrievalPolicyId:context.policy.policyId,retrievalPolicyVersion:context.policy.policyVersion,queryProjectorId:context.query.projectorId,queryProjectorVersion:context.query.projectorVersion,eligibleDocumentDigest:eligible.hash},budget:{limit:context.policy.contextCharacterBudget,used,remaining:context.policy.contextCharacterBudget-used,excludedCount:excluded.filter(x=>x.code==="CONTEXT_BUDGET_EXCLUDED").length}});
 }
}
const ex=(v:RankedKnowledgeRetrievalCandidate,code:"PER_DOCUMENT_LIMIT"|"CONTEXT_BUDGET_EXCLUDED",chunkIdentity=v.chunk.identity)=>({code,documentIdentity:v.document.identity,chunkIdentity,sourceTypes:v.candidate.sources.map(x=>x.type)} as const);
