import { KnowledgeDocumentRepository } from "../repositories/knowledge-document.repository.js";
import { KnowledgeChunkRepository } from "../repositories/knowledge-chunk.repository.js";
import { KnowledgeEmbeddingRepository } from "../repositories/knowledge-embedding.repository.js";
import { KnowledgeChunkSetVerificationService } from "./knowledge-chunk-set-verification.service.js";
import { freezeClone, validSourceSpan } from "./knowledge-document-admission.service.js";
import { calculateKnowledgeEmbeddingVectorDigest } from "./knowledge-embedding.service.js";
import type { KnowledgeRetrievalCandidate, KnowledgeRetrievalExclusion, KnowledgeRetrievalPolicy, KnowledgeRetrievalRequest, ValidatedKnowledgeRetrievalCandidate } from "../types/knowledge-retrieval.types.js";
export class KnowledgeRetrievalCandidateValidationService {
  public constructor(private readonly documents=new KnowledgeDocumentRepository(),private readonly chunks=new KnowledgeChunkRepository(),private readonly embeddings=new KnowledgeEmbeddingRepository(),private readonly verifier=new KnowledgeChunkSetVerificationService()){}
  public async validate(candidates:readonly KnowledgeRetrievalCandidate[],request:KnowledgeRetrievalRequest,policy?:KnowledgeRetrievalPolicy):Promise<Readonly<{valid:readonly ValidatedKnowledgeRetrievalCandidate[];excluded:readonly KnowledgeRetrievalExclusion[]}>>{
    const valid:ValidatedKnowledgeRetrievalCandidate[]=[];const excluded:KnowledgeRetrievalExclusion[]=[];
    for(const candidate of candidates){const sourceTypes=candidate.sources.map(x=>x.type);const reject=(code:KnowledgeRetrievalExclusion["code"])=>excluded.push({code,documentIdentity:candidate.documentIdentity,chunkIdentity:candidate.chunkIdentity,sourceTypes});
      if(!request.eligibleDocuments.some(x=>same(x,candidate.documentIdentity))){reject("DOCUMENT_NOT_ELIGIBLE");continue;}
      const dr=await this.documents.findExact(candidate.documentIdentity.documentId,candidate.documentIdentity.documentVersion);if(!dr.found){reject("DOCUMENT_NOT_FOUND");continue;}const d=dr.document;
      if(policy?.excludeSupersededMembers){let superseded=false;for(const identity of request.eligibleDocuments){if(same(identity,d.identity))continue;const other=await this.documents.findExact(identity.documentId,identity.documentVersion);if(other.found&&other.document.supersedes&&same(other.document.supersedes,d.identity)){superseded=true;break;}}if(superseded){reject("DOCUMENT_SUPERSEDED");continue;}}
      if(d.corpus!==request.scope.corpus){reject("CORPUS_MISMATCH");continue;}if(!request.scope.trustLevels.includes(d.trustLevel)){reject("TRUST_MISMATCH");continue;}if(request.scope.documentTypes&&!request.scope.documentTypes.includes(d.documentType)){reject("DOCUMENT_TYPE_MISMATCH");continue;}
      if((d.effectiveFrom&&d.effectiveFrom.getTime()>request.asOf.getTime())||(d.effectiveUntil&&request.asOf.getTime()>=d.effectiveUntil.getTime())){reject("DOCUMENT_OUTSIDE_EFFECTIVE_TIME");continue;}
      const cr=await this.chunks.findExact(candidate.chunkIdentity.chunkId,candidate.chunkIdentity.chunkVersion);if(!cr.found){reject("CHUNK_NOT_FOUND");continue;}const c=cr.chunk;if(!same(c.documentIdentity,d.identity)){reject("UNEXPECTED_CHUNK");continue;}
      const set=await this.verifier.readExactCompleteSet(d.identity,c.strategy);if(!set.verified){reject(set.code==="MANIFEST_NOT_FOUND"?"MANIFEST_NOT_FOUND":"CHUNK_SET_INCOMPLETE");continue;}if(!set.set.chunks.some(x=>same(x.identity,c.identity))){reject("CHUNK_NOT_FOUND");continue;}
      if(!validSourceSpan(c.sourceSpan)||!matchesFilters(c.metadata,request.filters)){reject(!validSourceSpan(c.sourceSpan)?"SOURCE_SPAN_INVALID":"METADATA_FILTER_MISMATCH");continue;}
      let failed=false;for(const source of candidate.sources){if(source.type!=="VECTOR")continue;const er=await this.embeddings.findExact(source.embeddingIdentity);if(!er.found){reject("EMBEDDING_NOT_FOUND");failed=true;break;}const e=er.embedding;const {vectorDigest,createdAt:_,...material}=e;if(!same(e.chunkIdentity,c.identity)||e.chunkContentDigest!==c.contentDigest||e.embeddingSchema.embeddingSchemaId!==request.embeddingSchema.embeddingSchemaId||e.embeddingSchema.embeddingSchemaVersion!==request.embeddingSchema.embeddingSchemaVersion){reject("EMBEDDING_LINEAGE_MISMATCH");failed=true;break;}if(calculateKnowledgeEmbeddingVectorDigest(material)!==vectorDigest){reject("VECTOR_DIGEST_MISMATCH");failed=true;break;}if(source.indexedChunkDigest!==c.contentDigest){reject("CHUNK_DIGEST_MISMATCH");failed=true;break;}if(source.indexedDocumentDigest&&source.indexedDocumentDigest!==d.contentDigest){reject("DOCUMENT_DIGEST_MISMATCH");failed=true;break;}if(source.indexedVectorDigest!==e.vectorDigest){reject("VECTOR_DIGEST_MISMATCH");failed=true;break;}}
      if(!failed)valid.push({candidate,document:d,chunk:c,verifiedChunks:set.set.chunks,chunkSetIdentity:set.set.manifest.identity});
    }return freezeClone({valid,excluded});
  }
}
const same=(a:{documentId?:string;documentVersion?:number;chunkId?:string;chunkVersion?:number},b:typeof a)=>JSON.stringify(a)===JSON.stringify(b);
const matchesFilters=(m:any,f:any)=>!f||(!f.factorKeys||f.factorKeys.every((v:string)=>m.factors.some((x:any)=>x.factorKey===v)))&&(!f.relationshipTypes||f.relationshipTypes.every((v:string)=>m.relationshipTypes.includes(v)))&&(!f.subjectTypes||f.subjectTypes.every((v:string)=>m.subjectTypes.includes(v)))&&(!f.topics||f.topics.every((v:string)=>m.topics.includes(v)))&&(!f.validationCodes||f.validationCodes.every((v:string)=>m.validationCodes.includes(v)))&&(!f.adrNumbers||f.adrNumbers.every((v:string)=>String(m.adr?.number)===v))&&(!f.exampleClassifications||f.exampleClassifications.includes(m.exampleClassification));
