import type { ScoringTemplateCrudService } from "./scoring-template-crud.service.js";
import type { TemplateDraftGenerationService } from "./template-draft-generation.service.js";
import type { TemplateDraftCandidateValidatorService } from "./template-draft-candidate-validator.service.js";
import type { TemplateDraftRegistryProjectionService } from "./template-draft-registry-projection.service.js";
import type { TemplateDraftAcceptanceValidatorService } from "./template-draft-acceptance-validator.service.js";
import type { TemplateDraftProjectionService } from "./template-draft-projection.service.js";
import type { AcceptTemplateDraftCandidateRequest } from "../types/template-draft-acceptance.types.js";
import type { TemplateDraftGenerationRequest, TemplateDraftGenerationResult } from "../types/template-draft-generation.types.js";
import type { TemplateDraftRegistryProjectionRequest } from "../types/template-draft-registry-projection.types.js";
import type { TemplateDraftProjectionResult } from "../types/template-draft-projection.types.js";
const freeze=<T>(v:T):T=>deep(structuredClone(v));const deep=<T>(v:T):T=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){for(const x of Object.values(v))deep(x);Object.freeze(v);}return v;};
export class TemplateDraftingWorkflowService {
  public constructor(private readonly d:Readonly<{generation:Pick<TemplateDraftGenerationService,"generate">;acceptance:TemplateDraftAcceptanceValidatorService;projection:TemplateDraftProjectionService;registryProjection:TemplateDraftRegistryProjectionService;validator:TemplateDraftCandidateValidatorService;templates:Pick<ScoringTemplateCrudService,"createUserDraft">}>){ }
  public generate(request:TemplateDraftGenerationRequest):Promise<TemplateDraftGenerationResult>{return this.d.generation.generate(request);}
  public async accept(input:Readonly<{acceptance:AcceptTemplateDraftCandidateRequest;generation:TemplateDraftGenerationResult;currentAuthorities:TemplateDraftRegistryProjectionRequest}>):Promise<TemplateDraftProjectionResult>{
    const base=lineage(input.acceptance,input.generation);if(input.generation.status!=="COMPLETED"&&input.generation.status!=="PARTIAL")return failure("ACCEPTANCE_VALIDATION_FAILED","GENERATION_NOT_ACCEPTABLE",base);
    let current;try{current=this.d.registryProjection.create(input.currentAuthorities);}catch{return failure("STALE_CANDIDATE","CURRENT_AUTHORITY_INVALID",base);}if(current.canonicalDigest!==input.acceptance.expectedRegistryProjection.projectionDigest||current.projectionId!==input.acceptance.expectedRegistryProjection.projectionId||current.projectionVersion!==input.acceptance.expectedRegistryProjection.projectionVersion)return failure("STALE_CANDIDATE","PROJECTION_CHANGED",base);
    const revalidated=this.d.validator.validate({draftingRequest:{requestId:input.generation.candidate.requestId,requestVersion:1,userPrompt:"Accepted transient candidate",operation:"CREATE_TEMPLATE",requestedConcepts:input.generation.reviewReport.requestedConcepts.map(c=>({conceptId:c.conceptId,text:c.text})),projectionIdentity:{projectionId:current.projectionId,projectionVersion:current.projectionVersion,projectionDigest:current.canonicalDigest}},candidate:input.generation.candidate,projection:current,currentAuthorities:input.currentAuthorities,validationPolicy:input.currentAuthorities.validationPolicy});
    if(revalidated.report.outcome==="VALIDATION_FAILED"||revalidated.validatedCandidate.supportedBindings.map(b=>b.bindingCandidateId).join("|")!==input.generation.validatedCandidate.supportedBindings.map(b=>b.bindingCandidateId).join("|"))return failure("STALE_CANDIDATE","CANDIDATE_DISPOSITION_CHANGED",base);
    const acceptance=this.d.acceptance.validate({acceptance:input.acceptance,generation:input.generation});if(!acceptance.valid)return failure(acceptance.code==="OWNERSHIP_FAILED"?"OWNERSHIP_FAILED":acceptance.code==="STALE_CANDIDATE"?"STALE_CANDIDATE":"ACCEPTANCE_VALIDATION_FAILED",acceptance.code,base);
    let projected;try{projected=this.d.projection.project({acceptance:input.acceptance,generation:input.generation,acceptedBindings:acceptance.acceptedBindings});}catch{return failure("ACCEPTANCE_VALIDATION_FAILED","PROJECTION_INVALID",base);}try{const created=await this.d.templates.createUserDraft(projected.command);const id=created.id??"";const finalLineage={...projected.lineage,createdTemplateId:id,createdTemplateVersion:created.version};return freeze({status:"CREATED",template:{id,templateKey:created.templateKey,version:created.version,scope:"USER",status:"DRAFT",ownerId:input.acceptance.authenticatedUserId},acceptedBindingIds:projected.acceptedBindingIds,excludedConceptIds:projected.excludedConceptIds,lineage:finalLineage});}catch{return failure("PERSISTENCE_FAILED","TEMPLATE_CREATE_FAILED",projected.lineage);}
  }
}
const lineage=(a:AcceptTemplateDraftCandidateRequest,g:TemplateDraftGenerationResult):any=>({requestId:a.requestId,candidateId:a.candidateId,candidateSchemaVersion:a.expectedCandidateSchemaVersion,generationAttemptId:g.generationLineage.generationAttemptId,promptId:g.generationLineage.promptId,promptVersion:g.generationLineage.promptVersion,registryProjectionId:a.expectedRegistryProjection.projectionId,registryProjectionVersion:a.expectedRegistryProjection.projectionVersion,registryProjectionDigest:a.expectedRegistryProjection.projectionDigest,validationPolicyId:a.expectedValidation.validationPolicyId,validationPolicyVersion:a.expectedValidation.validationPolicyVersion,acceptanceId:a.acceptanceId,acceptanceVersion:a.acceptanceVersion,authenticatedOwnerId:a.authenticatedUserId,acceptedBindingIds:[...a.acceptedBindingIds],excludedConceptIds:[],createdTemplateId:null,createdTemplateVersion:null});
const failure=(status:any,code:string,lineage:any):TemplateDraftProjectionResult=>freeze({status,issues:[{code,explanation:"The draft was not persisted."}],lineage});
