import { z } from "zod";
import type { FeatureFlagService } from "../config/feature-flags.js";
import type { TemplateDraftGenerationPort } from "../ports/template-draft-generation.port.js";
import type { CreateLlmTraceInput } from "../types/llm-trace.types.js";
import type { TemplateDraftGenerationRequest, TemplateDraftGenerationResult, TemplateDraftGenerationLineage } from "../types/template-draft-generation.types.js";
import type { TemplateDraftCandidate } from "../types/template-draft-candidate.types.js";
import type { TemplateDraftCandidateValidatorService } from "./template-draft-candidate-validator.service.js";
import type { TemplateDraftPromptContextService } from "./template-draft-prompt-context.service.js";
import type { TemplateDraftReviewReportService } from "./template-draft-review-report.service.js";
const id = z.string().trim().min(1).max(160); const conceptIds = z.array(id).max(24);
const subject = z.object({ type: z.string().optional(), key: z.string().optional(), displayName: z.string().optional() }).strict();
const citation = z.object({ citationHandle: z.string().min(1).max(160), purpose: z.enum(["FACTOR_EXPLANATION","RELATIONSHIP_EXPLANATION","EXAMPLE","LIMITATION","UNRESOLVED_CONCEPT","VALIDATION_GUIDANCE"]), claimTarget: z.object({ type: z.enum(["BINDING","UNRESOLVED_CONCEPT","CLARIFICATION","GENERAL"]), id }).strict() }).strict();
export const templateDraftCandidateSchema = z.object({ candidateId: id, candidateSchemaVersion: z.number().int().positive(), requestId: id,
  interpretedRequest: z.object({ title: z.string().optional(), description: z.string().optional(), intendedMarket: z.string().optional(), intendedHoldingPeriod: z.string().optional(), subject: subject.optional() }).strict(), requestedConceptIds: conceptIds,
  proposedBindings: z.array(z.object({ bindingCandidateId: id, requestedConceptIds: conceptIds, factorReference: z.object({ factorKey: z.string(), factorVersion: z.number().int().positive() }).strict().optional(), relationship: z.string().optional(), subjectBinding: subject.optional(), valueType: z.string().optional(), unit: z.string().nullable().optional(), missingDataPolicy: z.string().optional(), proposedWeight: z.number().finite().optional(), modelRationale: z.string().max(500).optional(), modelSupportClaim: z.enum(["SUPPORTED", "UNSUPPORTED"]).optional() }).strict()).max(24),
  proposedUnresolvedConcepts: z.array(z.object({ conceptId: id, requirements: z.array(z.string()).max(8), explanation: z.string().max(500).optional() }).strict()).max(24), proposedClarificationQuestions: z.array(z.object({ questionId: id, requestedConceptIds: conceptIds, question: z.string().min(1).max(500) }).strict()).max(24), generationWarnings: z.array(z.object({ warningId: id, requestedConceptIds: conceptIds, warning: z.string().min(1).max(500) }).strict()).max(24), citationReferences: z.array(citation).max(48).optional(),
  generationLineage: z.object({ generationAttemptId: id, modelProvider: z.string().min(1).max(120), modelName: z.string().min(1).max(120), promptId: id, promptVersion: z.number().int().positive(), registryProjectionId: id, registryProjectionVersion: z.number().int().positive(), registryProjectionDigest: z.string().regex(/^[a-f0-9]{64}$/) }).strict() }).strict();
type Trace = Pick<{ record(input: CreateLlmTraceInput): Promise<void> }, "record">;
export class TemplateDraftGenerationService {
  public constructor(private readonly d: Readonly<{ flags: Pick<FeatureFlagService, "isEnabled">; port: TemplateDraftGenerationPort; prompts: TemplateDraftPromptContextService; validator: TemplateDraftCandidateValidatorService; reviews: TemplateDraftReviewReportService; traces: Trace }>) {}
  public async generate(r: TemplateDraftGenerationRequest): Promise<TemplateDraftGenerationResult> {
    const base = lineage(r, null, null, null); if (!this.d.flags.isEnabled("RAG_TEMPLATE_DRAFTING_ENABLED")) return frozen({ status: "FEATURE_DISABLED", reasonCode: "TEMPLATE_DRAFTING_DISABLED", generationLineage: base });
    if (!validRequest(r)) return frozen({ status: "VALIDATION_FAILED", reasonCode: "INVALID_GENERATION_REQUEST", generationLineage: base });
    const context = this.d.prompts.build(r); const messages = this.d.prompts.messages(context); let model;
    try { model = await this.d.port.generate({ correlationId: r.generationAttemptId, schemaId: "TEMPLATE_DRAFT_CANDIDATE", schemaVersion: r.candidateSchemaVersion, messages, context }); } catch { model = { completed: false as const, code: "PROVIDER_FAILED" as const, provider: "UNKNOWN", model: null, completedAt: new Date(r.requestedAt.getTime()) }; }
    const completed = new Date(model.completedAt.getTime()); const line = lineage(r, model.provider, model.model, completed);
    if (!model.completed) { await trace(this.d.traces, r, line, model.code === "EMPTY_RESPONSE" ? "EMPTY_RESPONSE" : "PROVIDER_FAILED", model.code, false, false, undefined); return frozen({ status: "PROVIDER_FAILED", reasonCode: model.code, generationLineage: line }); }
    let raw: unknown = model.output; let parsed = true; if (typeof raw === "string") { try { raw = JSON.parse(raw); } catch { parsed = false; } }
    if (!parsed) { await trace(this.d.traces, r, line, "PARSE_FAILED", "TEMPLATE_DRAFT_PARSE_FAILED", false, false, model.tokenUsage); return frozen({ status: "VALIDATION_FAILED", reasonCode: "MALFORMED_MODEL_OUTPUT", generationLineage: line }); }
    const schema = templateDraftCandidateSchema.safeParse(raw); if (!schema.success) { await trace(this.d.traces, r, line, "VALIDATION_FAILED", "TEMPLATE_DRAFT_SCHEMA_INVALID", true, false, model.tokenUsage); return frozen({ status: "VALIDATION_FAILED", reasonCode: "MODEL_SCHEMA_INVALID", generationLineage: line }); }
    const candidate = schema.data as unknown as TemplateDraftCandidate; const validation = this.d.validator.validate({ draftingRequest: r.draftingRequest, candidate, projection: r.registryProjection, currentAuthorities: r.currentAuthorities, validationPolicy: r.currentAuthorities.validationPolicy });
    const review = this.d.reviews.project({ reportId: `${r.generationAttemptId}_REVIEW`, request: r.draftingRequest, candidate, validatedCandidate: validation.validatedCandidate, validation: validation.report, projection: r.registryProjection, promptId: r.promptIdentity.promptId, promptVersion: r.promptIdentity.promptVersion });
    await trace(this.d.traces, r, line, "COMPLETED", undefined, true, true, model.tokenUsage, validation.report);
    if (validation.report.outcome === "COMPLETED" || validation.report.outcome === "PARTIAL") return frozen({ status: validation.report.outcome, candidate, validation: validation.report, validatedCandidate: validation.validatedCandidate, reviewReport: review, generationLineage: line });
    return frozen({ status: validation.report.outcome, reasonCode: `CANDIDATE_${validation.report.outcome}`, generationLineage: line, reviewReport: review });
  }
}
const validRequest = (r: TemplateDraftGenerationRequest) => r && r.requestId === r.draftingRequest.requestId && r.promptIdentity.promptId.length > 0 && Number.isSafeInteger(r.promptIdentity.promptVersion) && r.promptIdentity.promptVersion > 0 && r.candidateSchemaVersion > 0 && r.requestedAt instanceof Date && Number.isFinite(r.requestedAt.getTime()) && r.registryProjection.projectionId === r.draftingRequest.projectionIdentity.projectionId && r.registryProjection.canonicalDigest === r.draftingRequest.projectionIdentity.projectionDigest;
const lineage = (r: TemplateDraftGenerationRequest, provider: string | null, model: string | null, completedAt: Date | null): TemplateDraftGenerationLineage => ({ requestId: r.requestId, generationAttemptId: r.generationAttemptId, provider, model, promptId: r.promptIdentity.promptId, promptVersion: r.promptIdentity.promptVersion, candidateSchemaVersion: r.candidateSchemaVersion, registryProjectionId: r.registryProjection.projectionId, registryProjectionVersion: r.registryProjection.projectionVersion, registryProjectionDigest: r.registryProjection.canonicalDigest, requestedAt: new Date(r.requestedAt.getTime()), completedAt });
const trace = async (service: Trace, r: TemplateDraftGenerationRequest, l: TemplateDraftGenerationLineage, status: CreateLlmTraceInput["status"], failureCode: string | undefined, parseSucceeded: boolean, schemaSucceeded: boolean, tokenUsage?: any, validation?: any) => { try { await service.record({ traceId: r.traceId, correlationId: r.generationAttemptId, taskType: "TEMPLATE_DRAFT_GENERATION", status, provider: l.provider ?? "UNKNOWN", ...(l.model ? { model: l.model } : {}), promptVersion: `${l.promptId}_V${l.promptVersion}`, schemaVersion: String(l.candidateSchemaVersion), startedAt: l.requestedAt, completedAt: l.completedAt ?? l.requestedAt, latencyMs: Math.max(0, (l.completedAt ?? l.requestedAt).getTime() - l.requestedAt.getTime()), ...(tokenUsage ? { tokenUsage } : {}), inputReference: { hash: l.registryProjectionDigest, redactedSummary: { requestedConceptCount: r.draftingRequest.requestedConcepts.length, projectionId: l.registryProjectionId, projectionVersion: l.registryProjectionVersion } }, ...(validation ? { outputReference: { fieldSummary: { supportedBindingCount: validation.counts.supportedBindings, unresolvedConceptCount: validation.counts.unresolvedConcepts, outcome: validation.outcome } } } : {}), validation: { parseSucceeded, schemaSucceeded, semanticSucceeded: validation ? validation.outcome !== "VALIDATION_FAILED" : false }, fallbackUsed: false, ...(failureCode ? { failureCode } : {}) }); } catch {} };
const frozen = <T>(v: T): T => deep(structuredClone(v)); const deep = <T>(v: T): T => { if (v && typeof v === "object" && !Object.isFrozen(v)) { for (const x of Object.values(v)) deep(x); Object.freeze(v); } return v; };
