import type { TemplateDraftCandidate, TemplateDraftingRequest } from "../types/template-draft-candidate.types.js";
import type { TemplateDraftRegistryProjection } from "../types/template-draft-registry-projection.types.js";
import type { TemplateDraftReviewReport } from "../types/template-draft-review-report.types.js";
import type { TemplateDraftValidationReport, ValidatedTemplateDraftCandidate } from "../types/template-draft-validation.types.js";
const LIMITATIONS = Object.freeze(["NON_AUTHORITATIVE_CANDIDATE", "WEIGHTS_REQUIRE_USER_INPUT", "NO_PERSISTENCE", "NO_RAG", "NO_RUNTIME_OR_COMPILATION_AUTHORITY"] as const);
const freeze = <T>(v: T): T => deepFreeze(structuredClone(v)); const deepFreeze = <T>(v: T): T => { if (v && typeof v === "object" && !Object.isFrozen(v)) { for (const x of Object.values(v)) deepFreeze(x); Object.freeze(v); } return v; };
export class TemplateDraftReviewReportService {
  public project(input: Readonly<{ reportId: string; request: TemplateDraftingRequest; candidate: TemplateDraftCandidate; validatedCandidate: ValidatedTemplateDraftCandidate; validation: TemplateDraftValidationReport; projection: TemplateDraftRegistryProjection; promptId: string; promptVersion: number }>): TemplateDraftReviewReport {
    const supportedIds = new Set(input.validatedCandidate.supportedBindings.flatMap((b) => b.requestedConceptIds)); const unresolved = new Map(input.validatedCandidate.unresolvedConcepts.map((v) => [v.conceptId, v])); const clarified = new Set(input.validatedCandidate.clarificationQuestions.flatMap((q) => q.requestedConceptIds));
    return freeze({ reportId: input.reportId, reportVersion: 1 as const, requestId: input.request.requestId, candidateId: input.candidate.candidateId, outcome: input.validation.outcome, interpretedRequest: input.validatedCandidate.interpretedRequest,
      requestedConcepts: input.request.requestedConcepts.map((c) => { const disposition = clarified.has(c.conceptId) ? "CLARIFICATION_REQUIRED" as const : unresolved.has(c.conceptId) ? "UNRESOLVED" as const : supportedIds.has(c.conceptId) ? "SUPPORTED" as const : "INVALID" as const; return { conceptId: c.conceptId, text: c.text, disposition, explanation: explanation(disposition, unresolved.get(c.conceptId)?.requirements ?? []) }; }),
      supportedBindings: input.validatedCandidate.supportedBindings.map((b) => { const factor = input.projection.factors.find((f) => f.factorKey === b.factorReference.factorKey && f.factorVersion === b.factorReference.factorVersion); return { bindingCandidateId: b.bindingCandidateId, requestedConceptIds: b.requestedConceptIds, factorKey: b.factorReference.factorKey, factorVersion: b.factorReference.factorVersion, relationship: b.relationship, subjectType: b.subjectBinding.type, subjectKey: b.subjectBinding.key, providerAvailable: (factor?.providers.length ?? 0) > 0, compilationSupport: b.compilationSupport, weightStatus: b.weightStatus }; }),
      unresolvedConcepts: input.validatedCandidate.unresolvedConcepts.map((c) => ({ conceptId: c.conceptId, requirements: c.requirements, explanation: `Unresolved: ${c.requirements.join(", ")}.` })), clarificationQuestions: input.validatedCandidate.clarificationQuestions, warnings: input.validatedCandidate.warnings, limitations: LIMITATIONS,
      lineage: { promptId: input.promptId, promptVersion: input.promptVersion, candidateSchemaVersion: input.candidate.candidateSchemaVersion, registryProjectionId: input.projection.projectionId, registryProjectionVersion: input.projection.projectionVersion, registryProjectionDigest: input.projection.canonicalDigest, validationPolicyId: input.validatedCandidate.validationLineage.validationPolicyId, validationPolicyVersion: input.validatedCandidate.validationLineage.validationPolicyVersion } });
  }
}
const explanation = (d: string, requirements: readonly string[]) => d === "SUPPORTED" ? "Supported by exact deterministic authority validation." : d === "CLARIFICATION_REQUIRED" ? "Clarification is required before this concept can be resolved." : d === "UNRESOLVED" ? `Unresolved requirements: ${requirements.join(", ")}.` : "Candidate structure or authority validation failed.";
