import type { TemplateDraftCreateCommand, TemplateDraftProjectionLineage, TemplateDraftProjectionRequest } from "../types/template-draft-projection.types.js";
const freeze=<T>(v:T):T=>deepFreeze(structuredClone(v));const deepFreeze=<T>(v:T):T=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){for(const x of Object.values(v))deepFreeze(x);Object.freeze(v);}return v;};
export class TemplateDraftProjectionService {
  public project(input: TemplateDraftProjectionRequest): Readonly<{ command: TemplateDraftCreateCommand; acceptedBindingIds: readonly string[]; excludedConceptIds: readonly string[]; lineage: TemplateDraftProjectionLineage }> {
    const weights=new Map(input.acceptedBindings.map(v=>[v.bindingCandidateId,v.weight]));const selected=input.generation.validatedCandidate.supportedBindings.filter(b=>weights.has(b.bindingCandidateId));if(selected.length!==input.acceptedBindings.length)throw new Error("ACCEPTED_BINDING_NOT_SUPPORTED");
    const acceptedConcepts=new Set(selected.flatMap(b=>b.requestedConceptIds));const allConcepts=input.generation.reviewReport.requestedConcepts.map(c=>c.conceptId);const excludedConceptIds=allConcepts.filter(id=>!acceptedConcepts.has(id));
    const sections=[{sectionKey:"AI_DRAFT_FACTORS",label:"Accepted draft factors",weight:100,enabled:true,missingDataPolicy:selected.some(b=>b.missingDataPolicy==="BLOCK")?"BLOCK" as const:"PARTIAL" as const,evaluators:selected.map(b=>({evaluatorKey:`GENERIC_FACTOR:${b.factorReference.factorKey}`,label:b.modelRationale??b.factorReference.factorKey,weight:weights.get(b.bindingCandidateId)!,enabled:true,missingDataPolicy:b.missingDataPolicy,config:{relationshipType:b.relationship,subjectBinding:{...b.subjectBinding},factorVersion:b.factorReference.factorVersion}}))}];
    const a=input.acceptance,g=input.generation;const lineage:TemplateDraftProjectionLineage={requestId:a.requestId,candidateId:a.candidateId,candidateSchemaVersion:a.expectedCandidateSchemaVersion,generationAttemptId:g.generationLineage.generationAttemptId,promptId:g.generationLineage.promptId,promptVersion:g.generationLineage.promptVersion,registryProjectionId:a.expectedRegistryProjection.projectionId,registryProjectionVersion:a.expectedRegistryProjection.projectionVersion,registryProjectionDigest:a.expectedRegistryProjection.projectionDigest,validationPolicyId:a.expectedValidation.validationPolicyId,validationPolicyVersion:a.expectedValidation.validationPolicyVersion,acceptanceId:a.acceptanceId,acceptanceVersion:a.acceptanceVersion,authenticatedOwnerId:a.authenticatedUserId,acceptedBindingIds:[...a.acceptedBindingIds],excludedConceptIds,createdTemplateId:null,createdTemplateVersion:null};
    return freeze({command:{userId:a.authenticatedUserId,templateKey:`USER_AI_DRAFT_${a.acceptanceId}`.toUpperCase(),baseTemplateKey:a.template.baseTemplateKey,templateName:a.template.templateName,...(a.template.description?{description:a.template.description}:{}),marketType:a.template.marketType,tradeStyle:a.template.tradeStyle,instrumentType:a.template.instrumentType,sections},acceptedBindingIds:a.acceptedBindingIds,excludedConceptIds,lineage});
  }
}
