import type { FactorDecisionBandPolicyService } from "../services/scoring/factor-decision-band-policy.service.js";
import { VersionedDecisionBandPolicyRegistryError, type DecisionBandPolicyRegistration, type VersionedDecisionBandPolicy, type VersionedDecisionBandPolicyRegistry } from "../types/versioned-decision-band-policy.types.js";
import { ImmutableHistoricalAuthority } from "./historical-authority.internal.js";
const ID = /^[A-Z0-9_]{1,120}$/;
export const DEFAULT_VERSIONED_DECISION_BAND_POLICIES: readonly DecisionBandPolicyRegistration[] = Object.freeze([]);
export class StaticVersionedDecisionBandPolicyRegistry implements VersionedDecisionBandPolicyRegistry {
  private readonly authority: ImmutableHistoricalAuthority<VersionedDecisionBandPolicy>;
  public constructor(values: readonly DecisionBandPolicyRegistration[], validator: Pick<FactorDecisionBandPolicyService, "validate">) { if (!Array.isArray(values) || !dense(values) || !validator || typeof validator.validate !== "function") throw new VersionedDecisionBandPolicyRegistryError("INVALID_COLLECTION"); const seen = new Set<string>(); const entries = []; for (const value of values as readonly unknown[]) { if (!record(value) || !record(value.definition) || !positive(value.definition.decisionBandPolicyVersion)) throw new VersionedDecisionBandPolicyRegistryError("INVALID_POLICY"); const result = validator.validate({ policy: value.definition, normalizationPolicy: value.normalizationPolicy }); if (!result.valid) throw new VersionedDecisionBandPolicyRegistryError("INVALID_POLICY"); if (typeof value.compileEligible !== "boolean") throw new VersionedDecisionBandPolicyRegistryError("INVALID_COMPILE_ELIGIBILITY"); const key = `${result.policy.decisionBandPolicyId}:${result.policy.decisionBandPolicyVersion}`; if (seen.has(key)) throw new VersionedDecisionBandPolicyRegistryError("DUPLICATE_VERSION"); seen.add(key); entries.push({ id: result.policy.decisionBandPolicyId, version: result.policy.decisionBandPolicyVersion, value: { definition: result.policy, compileEligible: value.compileEligible } }); } this.authority = new ImmutableHistoricalAuthority(entries); }
  public getExact(id: string, version: number) { return identifier(id) && positive(version) ? this.authority.getExact(id, version) : null; } public getLatest(id: string) { return identifier(id) ? this.authority.getLatest(id) : null; } public listVersions(id: string) { return identifier(id) ? this.authority.listVersions(id) : Object.freeze([]); }
}
const identifier = (v: unknown): v is string => typeof v === "string" && ID.test(v); const positive = (v: unknown): v is number => Number.isSafeInteger(v) && (v as number) > 0; const record = (v: unknown): v is Record<string, any> => typeof v === "object" && v !== null && !Array.isArray(v); const dense = (v: readonly unknown[]) => v.every((_, i) => i in v);
