import type { FactorAggregateNormalizationPolicyService } from "../services/scoring/factor-aggregate-normalization-policy.service.js";
import { VersionedNormalizationPolicyRegistryError, type NormalizationPolicyRegistration, type VersionedNormalizationPolicy, type VersionedNormalizationPolicyRegistry } from "../types/versioned-normalization-policy.types.js";
import { ImmutableHistoricalAuthority } from "./historical-authority.internal.js";
const ID = /^[A-Z0-9_]{1,120}$/;
export const DEFAULT_VERSIONED_NORMALIZATION_POLICIES: readonly NormalizationPolicyRegistration[] = Object.freeze([]);
export class StaticVersionedNormalizationPolicyRegistry implements VersionedNormalizationPolicyRegistry {
  private readonly authority: ImmutableHistoricalAuthority<VersionedNormalizationPolicy>;
  public constructor(values: readonly NormalizationPolicyRegistration[], validator: Pick<FactorAggregateNormalizationPolicyService, "validate">) { if (!Array.isArray(values) || !dense(values) || !validator || typeof validator.validate !== "function") throw new VersionedNormalizationPolicyRegistryError("INVALID_COLLECTION"); const seen = new Set<string>(); const entries = []; for (const value of values as readonly unknown[]) { if (!record(value) || !record(value.definition) || !positive(value.definition.normalizationPolicyVersion)) throw new VersionedNormalizationPolicyRegistryError("INVALID_POLICY"); const result = validator.validate({ policy: value.definition, aggregationPolicy: value.aggregationPolicy }); if (!result.valid) throw new VersionedNormalizationPolicyRegistryError("INVALID_POLICY"); if (typeof value.compileEligible !== "boolean") throw new VersionedNormalizationPolicyRegistryError("INVALID_COMPILE_ELIGIBILITY"); const key = `${result.policy.normalizationPolicyId}:${result.policy.normalizationPolicyVersion}`; if (seen.has(key)) throw new VersionedNormalizationPolicyRegistryError("DUPLICATE_VERSION"); seen.add(key); entries.push({ id: result.policy.normalizationPolicyId, version: result.policy.normalizationPolicyVersion, value: { definition: result.policy, compileEligible: value.compileEligible } }); } this.authority = new ImmutableHistoricalAuthority(entries); }
  public getExact(id: string, version: number) { return identifier(id) && positive(version) ? this.authority.getExact(id, version) : null; } public getLatest(id: string) { return identifier(id) ? this.authority.getLatest(id) : null; } public listVersions(id: string) { return identifier(id) ? this.authority.listVersions(id) : Object.freeze([]); }
}
const identifier = (v: unknown): v is string => typeof v === "string" && ID.test(v); const positive = (v: unknown): v is number => Number.isSafeInteger(v) && (v as number) > 0; const record = (v: unknown): v is Record<string, any> => typeof v === "object" && v !== null && !Array.isArray(v); const dense = (v: readonly unknown[]) => v.every((_, i) => i in v);
