import assert from "node:assert/strict";
import test from "node:test";
import { BTC_ETF_FLOW_CHARACTERIZATION_PROVIDER_KEY, StaticProviderAuthorityRegistry, createDefaultProviderAuthorityRegistry } from "../../../src/registries/provider-authority.registry.js";
import { ProviderAuthorityRegistryError } from "../../../src/types/provider-authority-registration.types.js";

const live = () => ({ providerDefinition: { providerKey: "BINANCE", displayName: "Binance", providerType: "DIRECT" as const, authorityLevel: "EXCHANGE" as const, costTier: "FREE" as const, supportedFactorKeys: ["MARKET.PRICE" as const], enabled: true }, evidenceProvenanceProvider: "binance-public-price", capabilities: { compileEligible: true, liveExecutionEligible: true, replayFixtureEligible: true } });

test("characterization provenance is canonical, replay eligible, non-live, and immutable", () => { const registry = createDefaultProviderAuthorityRegistry(); const authority = registry.getExact(BTC_ETF_FLOW_CHARACTERIZATION_PROVIDER_KEY)!; assert.equal(authority.evidenceProvenanceProvider, "yudiji-internal-btc-etf-flow-characterization"); assert.deepEqual(authority.capabilities, { compileEligible: true, liveExecutionEligible: false, replayFixtureEligible: true }); assert(Object.isFrozen(authority) && Object.isFrozen(authority.providerDefinition) && Object.isFrozen(authority.capabilities)); assert.notEqual(authority, registry.getExact(BTC_ETF_FLOW_CHARACTERIZATION_PROVIDER_KEY)); });
test("existing live-provider provenance and execution capability remain independent", () => { const authority = new StaticProviderAuthorityRegistry([live()]).getExact("BINANCE")!; assert.equal(authority.evidenceProvenanceProvider, "binance-public-price"); assert.equal(authority.capabilities.liveExecutionEligible, true); assert.equal(authority.capabilities.replayFixtureEligible, true); });
test("invalid provenance and duplicate provider identities fail closed", () => { for (const evidenceProvenanceProvider of ["", " provider", "provider ", "x".repeat(121)]) assert.throws(() => new StaticProviderAuthorityRegistry([{ ...live(), evidenceProvenanceProvider }]), (error: unknown) => error instanceof ProviderAuthorityRegistryError && error.code === "INVALID_REGISTRATION"); assert.throws(() => new StaticProviderAuthorityRegistry([live(), live()]), (error: unknown) => error instanceof ProviderAuthorityRegistryError && error.code === "DUPLICATE_PROVIDER"); });
