import assert from "node:assert/strict";
import test from "node:test";
import { DEFAULT_PROVIDER_RESOLUTION_RUNNER_REGISTRATIONS, ProviderResolutionRunnerRegistry, createDefaultProviderResolutionRunnerRegistry } from "../../../src/registries/provider-resolution-runner.registry.js";
import { ProviderResolutionRunnerRegistryError } from "../../../src/types/provider-resolution-composition.types.js";

const runner = { run: async () => ({ providerKey: "RUNNER_A", status: "COMPLETED" as const, candidateCount: 0, createdCount: 0, duplicateCount: 0, rejectedCount: 0, failedCount: 0, results: [] }) };
const registration = (providerKey = "PROVIDER_A", runnerId = "RUNNER_A", implementation = runner) => ({ providerKey, runnerId, runner: implementation });

test("accepts an empty registry with no production auto-discovery", () => { const registry = createDefaultProviderResolutionRunnerRegistry(); assert.equal(registry.get("PROVIDER_A"), null); assert.deepEqual(DEFAULT_PROVIDER_RESOLUTION_RUNNER_REGISTRATIONS, []); assert(Object.isFrozen(DEFAULT_PROVIDER_RESOLUTION_RUNNER_REGISTRATIONS)); });
test("uses exact provider-key lookup and returns the frozen registration", () => { const registry = new ProviderResolutionRunnerRegistry([registration()]); const found = registry.get("PROVIDER_A"); assert(found); assert.equal(found.runner, runner); assert(Object.isFrozen(found)); for (const key of ["provider_a", " PROVIDER_A", "PROVIDER_A ", "RUNNER_A", "UNKNOWN"]) assert.equal(registry.get(key), null); });
test("rejects invalid collections and registrations", () => { for (const value of [null, {}, "x", new Array(1)]) assert.throws(() => new ProviderResolutionRunnerRegistry(value as never), (error: unknown) => error instanceof ProviderResolutionRunnerRegistryError); for (const value of [{}, registration("bad"), registration("PROVIDER_A", " bad"), { providerKey: "PROVIDER_A", runnerId: "RUNNER_A", runner: {} }]) assert.throws(() => new ProviderResolutionRunnerRegistry([value as never]), (error: unknown) => error instanceof ProviderResolutionRunnerRegistryError && error.code === "INVALID_REGISTRATION"); });
test("rejects duplicate provider keys and runner identities", () => { assert.throws(() => new ProviderResolutionRunnerRegistry([registration(), registration("PROVIDER_A", "RUNNER_B")]), (e: unknown) => e instanceof ProviderResolutionRunnerRegistryError && e.code === "DUPLICATE_PROVIDER_KEY"); assert.throws(() => new ProviderResolutionRunnerRegistry([registration(), registration("PROVIDER_B", "RUNNER_A")]), (e: unknown) => e instanceof ProviderResolutionRunnerRegistryError && e.code === "DUPLICATE_RUNNER_ID"); });
test("source mutation cannot alter deterministic registry snapshots", () => { const source = [registration()]; const registry = new ProviderResolutionRunnerRegistry(source); source.length = 0; source.push(registration("PROVIDER_B", "RUNNER_B")); assert.equal(registry.get("PROVIDER_A")?.runnerId, "RUNNER_A"); assert.equal(registry.get("PROVIDER_B"), null); assert.equal(registry.get("PROVIDER_A"), registry.get("PROVIDER_A")); });

