import assert from "node:assert/strict"; import test from "node:test";
import { DEFAULT_FACTOR_DEFINITIONS } from "../../../src/registries/default-factor-definitions.js";
import { StaticVersionedFactorDefinitionRegistry, createDefaultVersionedFactorDefinitionRegistry } from "../../../src/registries/versioned-factor-definition.registry.js";
import { VersionedFactorDefinitionRegistryError } from "../../../src/types/versioned-factor-definition.types.js";
const wrap = (definition: any, compileEligible = true) => ({ definition, compileEligible });
test("default authority resolves both audited v1 definitions exactly", () => { const r = createDefaultVersionedFactorDefinitionRegistry(); assert.equal(r.getExact("MARKET.PRICE", 1)?.definition.factorKey, "MARKET.PRICE"); assert.equal(r.getExact("CRYPTO.ETF_NET_FLOW", 1)?.definition.version, 1); assert.equal(r.getExact("MARKET.PRICE", 2), null); });
test("multiple versions retain history and sort deterministically", () => { const v1 = DEFAULT_FACTOR_DEFINITIONS[0]!; const v2 = { ...v1, version: 2, displayName: "Market Price v2" }; const r = new StaticVersionedFactorDefinitionRegistry([wrap(v2), wrap(v1)]); assert.deepEqual(r.listVersions("MARKET.PRICE").map((v) => v.definition.version), [1, 2]); assert.equal(r.getLatest("MARKET.PRICE")?.definition.version, 2); assert.equal(r.getExact("MARKET.PRICE", 1)?.definition.displayName, "Market Price"); });
test("duplicates, invalid definitions, and invalid eligibility fail", () => { assert.throws(() => new StaticVersionedFactorDefinitionRegistry([wrap(DEFAULT_FACTOR_DEFINITIONS[0]), wrap(DEFAULT_FACTOR_DEFINITIONS[0])]), (e: unknown) => e instanceof VersionedFactorDefinitionRegistryError && e.code === "DUPLICATE_VERSION"); assert.throws(() => new StaticVersionedFactorDefinitionRegistry([wrap({ ...DEFAULT_FACTOR_DEFINITIONS[0], version: 0 })]), (e: unknown) => e instanceof VersionedFactorDefinitionRegistryError && e.code === "INVALID_DEFINITION"); assert.throws(() => new StaticVersionedFactorDefinitionRegistry([{ ...wrap(DEFAULT_FACTOR_DEFINITIONS[0]), compileEligible: "yes" } as never]), (e: unknown) => e instanceof VersionedFactorDefinitionRegistryError && e.code === "INVALID_COMPILE_ELIGIBILITY"); });
test("input and output are deeply immutable and detached", () => { const source: any = structuredClone(DEFAULT_FACTOR_DEFINITIONS[1]); const r = new StaticVersionedFactorDefinitionRegistry([wrap(source)]); source.displayName = "changed"; source.unit.allowedUnits.push("EUR"); const out = r.getExact("CRYPTO.ETF_NET_FLOW", 1)!; assert.equal(out.definition.displayName, "Crypto ETF Net Flow"); assert.deepEqual((out.definition.unit as any).allowedUnits, ["USD"]); assert(Object.isFrozen(out) && Object.isFrozen(out.definition) && Object.isFrozen((out.definition.unit as any).allowedUnits)); });
