import assert from "node:assert/strict"; import test from "node:test";
import { StaticVersionedDecisionBandPolicyRegistry } from "../../../src/registries/versioned-decision-band-policy.registry.js"; import { FactorDecisionBandPolicyService } from "../../../src/services/factor-decision-band-policy.service.js"; import { VersionedDecisionBandPolicyRegistryError } from "../../../src/types/versioned-decision-band-policy.types.js";
const normalization: any = { normalizationPolicyId: "DEFAULT_NORMALIZATION", normalizationPolicyVersion: 1, aggregationPolicyId: "DEFAULT_AGGREGATION", aggregationPolicyVersion: 1, factorKey: "CRYPTO.ETF_NET_FLOW", method: "PIECEWISE_LINEAR_ZERO_ANCHORED", sourceRange: { minimumPoints: -2, neutralPoints: 0, maximumPoints: 2 }, targetRange: { minimumScore: 0, neutralScore: 50, maximumScore: 100 }, outOfRangePolicy: "FAIL", precisionPolicy: "PRESERVE_NATIVE" };
const bands = () => ["STRONG_NEGATIVE", "NEGATIVE", "NEUTRAL", "POSITIVE", "STRONG_POSITIVE"].map((label, i) => ({ order: i + 1, label, minimumScore: i * 20, maximumScore: (i + 1) * 20, minimumInclusive: true, maximumInclusive: i === 4 }));
const policy = (version = 1) => ({ decisionBandPolicyId: "DEFAULT_DECISION_BANDS", decisionBandPolicyVersion: version, normalizationPolicyId: "DEFAULT_NORMALIZATION", normalizationPolicyVersion: 1, factorKey: "CRYPTO.ETF_NET_FLOW" as const, normalizedRange: { minimumScore: 0, maximumScore: 100 }, bands: bands() });
const reg = (values: any[]) => new StaticVersionedDecisionBandPolicyRegistry(values, new FactorDecisionBandPolicyService());
test("exact historical versions remain available in ascending order", () => { const r = reg([{ definition: policy(2), normalizationPolicy: normalization, compileEligible: false }, { definition: policy(), normalizationPolicy: normalization, compileEligible: true }]); assert.deepEqual(r.listVersions("DEFAULT_DECISION_BANDS").map((v) => v.definition.decisionBandPolicyVersion), [1, 2]); assert.equal(r.getLatest("DEFAULT_DECISION_BANDS")?.definition.decisionBandPolicyVersion, 2); assert.equal(r.getExact("DEFAULT_DECISION_BANDS", 1)?.compileEligible, true); });
test("canonical band validation, duplicates and eligibility fail", () => { const invalid = policy(); invalid.bands[1]!.minimumScore = 21; assert.throws(() => reg([{ definition: invalid, normalizationPolicy: normalization, compileEligible: true }]), (e: unknown) => e instanceof VersionedDecisionBandPolicyRegistryError && e.code === "INVALID_POLICY"); assert.throws(() => reg([{ definition: policy(), normalizationPolicy: normalization, compileEligible: true }, { definition: policy(), normalizationPolicy: normalization, compileEligible: true }]), (e: unknown) => e instanceof VersionedDecisionBandPolicyRegistryError && e.code === "DUPLICATE_VERSION"); assert.throws(() => reg([{ definition: policy(), normalizationPolicy: normalization, compileEligible: "true" }]), (e: unknown) => e instanceof VersionedDecisionBandPolicyRegistryError && e.code === "INVALID_COMPILE_ELIGIBILITY"); });
test("normalization context is not stored and bands are deeply frozen", () => { const out = reg([{ definition: policy(), normalizationPolicy: normalization, compileEligible: true }]).getExact("DEFAULT_DECISION_BANDS", 1)!; assert.equal("normalizationPolicy" in out, false); assert(Object.isFrozen(out) && Object.isFrozen(out.definition.bands) && Object.isFrozen(out.definition.bands[0])); assert.throws(() => (out.definition.bands as any[]).push({}), TypeError); });
