name: Deploy Backend to AWS Production

on:
  push:
    branches: [ "main" ]
    paths:
      - "yujidi-server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into AWS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Enter the project folder
            cd ~/Project-YuDIJI_Crypto/yujidi-server

            # 2. Pull the latest code
            git pull origin main

            # 3. Install packages
            npm install

            # 4. Restart the engine
            pm2 restart yujidi-engine
